import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { Alert, Button, Card, Checkbox, Descriptions, Drawer, Empty, Form, Input, InputNumber, Modal, Radio, Select, Space, Steps, Table, Tabs, Tag, Typography, message } from 'antd'
import { ArrowLeftOutlined, ArrowRightOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import { useCurrentAccount, usePerm } from '../perm'
import { useSession } from '../auth'
import { clone, countries, countrySummary, formatDate, makeId, platformSummary, STORAGE_KEY } from '../abTestConfig'
import type { ABStore, Plan, Target } from '../abTestConfig'
import { APP_CONFIG_KEY, audienceTarget, getSlot, seedAppStore, statusLabels } from '../appConfigModel'
import type { AppExperiment, Audience } from '../appConfigModel'
import { blankPlan, changeExperimentStatus, endOnline, experimentErrors, infoErrors, newExperiment, newOnline, planErrors, publishOnline, relatedTo, saveOnlineDraft, saveVisualExperiment, workspace } from '../appBusinessConfig'
import type { BusinessSnapshot, BusinessStore, ExperimentPlans, OnlinePlan } from '../appBusinessConfig'
import ABVisualPlanEditor from '../components/ABVisualPlanEditor'
import ABUnitEditor from '../components/ABUnitEditor'
import ABPlanEditor from '../components/ABPlanEditor'
import ABHistoryDrawer from '../components/ABHistoryDrawer'
import './AppABTest.css'
import './AppConfigWorkbench.css'
const {Title,Text}=Typography
const statusColor=(s:string)=>({ACTIVE:'green',RUNNING:'green',READY:'blue',PAUSED:'orange',TERMINATED:'red'}[s]??'default')
function load():BusinessStore {try{const s=JSON.parse(localStorage.getItem(APP_CONFIG_KEY)??'null');if(s?.schema===3&&['definitions','versions','releases','experiments','audit'].every(k=>Array.isArray(s[k])))return s}catch{}return seedAppStore()}
function AudienceFields({value,onChange,readOnly}:{value:Audience;onChange:(a:Audience)=>void;readOnly:boolean}){return <div className="ab-two-fields"><Form.Item label="国家（用户当前 IP）" required><Select aria-label="适用国家" disabled={readOnly} mode="multiple" value={value.countries} options={countries} onChange={v=>onChange({...value,countries:v.includes('*')?v[v.length-1]==='*'?['*']:v.filter(x=>x!=='*'):v})}/></Form.Item><Form.Item label="App 终端" required><Checkbox.Group aria-label="适用终端" disabled={readOnly} value={value.platforms} options={['iOS','Android']} onChange={v=>onChange({...value,platforms:v as Audience['platforms']})}/></Form.Item></div>}
type Edit = {kind:'online';value:OnlinePlan}|{kind:'experiment';value:AppExperiment;visual:ExperimentPlans}
export default function AppConfigWorkbench(){
 const [store,setStore]=useState(load),[tab,setTab]=useState('online'),[editing,setEditing]=useState<Edit|null>(null),[step,setStep]=useState(0),[dirty,setDirty]=useState(false),[readOnly,setReadOnly]=useState(false),[showErrors,setShowErrors]=useState(false),[publishError,setPublishError]=useState('')
 const [search,setSearch]=useState(''),[country,setCountry]=useState<string>(),[platform,setPlatform]=useState<string>(),[status,setStatus]=useState<string>(),[related,setRelated]=useState<OnlinePlan|null>(null),[page,setPage]=useState(1)
 const [activeGroup,setActiveGroup]=useState(''),[history,setHistory]=useState<{id:string;name:string;versionIds:string[];releaseIds:string[]}|null>(null),[snapshot,setSnapshot]=useState<BusinessSnapshot|null>(null),[unitPreview,setUnitPreview]=useState<string>(),[archive,setArchive]=useState(false)
 const [legacyPreview,setLegacyPreview]=useState<{plan:Plan;target:Target;name:string}|null>(null),[legacyHistory,setLegacyHistory]=useState<{kind:'online'|'experiment';id:string;name:string}|null>(null)
 const loaded=useRef(localStorage.getItem(APP_CONFIG_KEY)),root=useRef<HTMLDivElement>(null),[footer,setFooter]=useState({left:0,width:0})
 const [api,holder]=message.useMessage(),[modal,modalHolder]=Modal.useModal(),{account}=useCurrentAccount(),session=useSession(),canEdit=usePerm().isOperate('appABTest')
 const actor=account?`${account.name}（${account.email}）`:session?.email??'当前操作人',w=workspace(store)
 const online=editing?.kind==='online'?editing.value:null,exp=editing?.kind==='experiment'?editing.value:null,visual=editing?.kind==='experiment'?editing.visual:null
 const locked=readOnly||!canEdit||!!exp&&exp.status!=='DRAFT'
 const group=exp?.groups.find(g=>g.id===activeGroup)??exp?.groups[0]
 const legacy:ABStore=(()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)??'null')??{version:2,online:[],experiments:[]}}catch{return {version:2,online:[],experiments:[]}}})()
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
 useLayoutEffect(()=>{if(!editing||!root.current)return;const measure=()=>{const r=root.current!.getBoundingClientRect();setFooter({left:r.left,width:r.width})};measure();const observer=new ResizeObserver(measure);observer.observe(root.current);window.addEventListener('resize',measure);return()=>{observer.disconnect();window.removeEventListener('resize',measure)}},[!!editing])
 const persist=(next:BusinessStore)=>{if(!canEdit)throw Error('当前账号仅可查看。');if(localStorage.getItem(APP_CONFIG_KEY)!==loaded.current)throw Error('其他窗口已更新配置，请刷新后再操作。');const raw=JSON.stringify(next);localStorage.setItem(APP_CONFIG_KEY,raw);loaded.current=raw;setStore(next)}
 const act=(fn:()=>void)=>{try{fn()}catch(e){api.error((e as Error).message)}}
 const reset=()=>{setSearch('');setCountry(undefined);setPlatform(undefined);setStatus(undefined);setRelated(null);setPage(1)}
 const open=(item:Edit,readonly=false)=>{setEditing(clone(item));setReadOnly(readonly);setDirty(false);setStep(0);setShowErrors(false);setPublishError('');if(item.kind==='experiment')setActiveGroup(item.value.groups[0]?.id??'');root.current?.scrollIntoView({block:'start'})}
 const editOnline=(p:OnlinePlan)=>open({kind:'online',value:clone(w.drafts.find(x=>x.id===p.id)??{...p,status:'DRAFT',replaceId:p.status==='DRAFT'?undefined:p.id})})
 const createExperiment=(base?:OnlinePlan)=>{const e=newExperiment(base);open({kind:'experiment',...e})}
 const updateOnline=(patch:Partial<OnlinePlan>)=>{if(!locked&&online){setEditing({kind:'online',value:{...online,...patch}});setDirty(true)}}
 const updateExperiment=(patch:Partial<AppExperiment>,v=visual!)=>{if(!locked&&exp){setEditing({kind:'experiment',value:{...exp,...patch},visual:v});setDirty(true)}}
 const back=()=>{if(dirty)modal.confirm({title:'离开当前编辑？',content:'未保存的修改不会进入编辑历史。',okText:'放弃并返回',cancelText:'继续编辑',onOk:()=>{setEditing(null);setDirty(false)}});else setEditing(null)}
 const info=editing?infoErrors(editing.value):[],content=online?planErrors(online.plan):exp&&visual?experimentErrors(store,exp,visual):[]
 const errors=[info,content,[...info,...content]]
 const go=(next:number)=>{if(next>step&&!locked){for(let i=0;i<next;i++)if(errors[i].length){setStep(i);setShowErrors(true);api.error('请先修正本步骤的问题');return}}setStep(next);setShowErrors(false);root.current?.scrollIntoView({block:'start'})}
 const saveDraft=()=>act(()=>{if(locked)return;persist(online?saveOnlineDraft(store,online,actor):saveVisualExperiment(store,exp!,visual!,actor));setDirty(false);api.success('草稿已保存，线上内容不受影响')})
 const finish=()=>{try{if(locked)return;if(errors[2].length){setShowErrors(true);return}persist(online?publishOnline(store,online,actor):saveVisualExperiment(store,exp!,visual!,actor,true));setDirty(false);setEditing(null);setTab(online?'online':'experiment');api.success(online?'线上配置已发布（原型演示）':'实验已就绪，可以启动')}catch(e){setPublishError((e as Error).message)}}
 const switchStatus=(e:AppExperiment,next:AppExperiment['status'])=>modal.confirm({title:`${next==='DRAFT'?'退回草稿':next==='RUNNING'?(e.status==='PAUSED'?'恢复':'启动'):statusLabels[next]}「${e.name}」？`,content:next==='DRAFT'?'退回后可继续编辑各组页面。':'实验启动后，分组比例、流程、页面和素材保持冻结；结束后不能恢复。',okText:'确认',cancelText:'取消',onOk:()=>act(()=>persist(changeExperimentStatus(store,e,next,actor)))})
 const matches=(a:Audience)=> (!country||a.countries.includes('*')||a.countries.includes(country))&&(!platform||a.platforms.includes(platform as 'iOS'|'Android'))
 const rows=[...w.online,...w.drafts.filter(d=>!w.online.some(x=>x.id===d.id))].filter(p=>p.name.includes(search)&&matches(p.audience)&&(!status||p.status===status))
 const experimentRows=store.experiments.filter(e=>e.name.includes(search)&&matches(e.audience)&&(!status||e.status===status)&&(!related||relatedTo(store,related).some(x=>x.id===e.id)))
 const scopeColumns=[{title:'国家',width:140,render:(_:unknown,p:{audience:Audience})=>countrySummary(audienceTarget(p.audience))},{title:'终端',width:100,render:(_:unknown,p:{audience:Audience})=>platformSummary(audienceTarget(p.audience))},{title:'版本范围',width:130,render:(_:unknown,p:{minVersion:string})=>`${p.minVersion} 及以上`}]
 const openHistory=(p:OnlinePlan|AppExperiment)=>setHistory({id:p.id,name:p.name,versionIds:'versionIds'in p?p.versionIds:p.groups.flatMap(g=>g.bindings.map(b=>b.versionId)),releaseIds:'releaseIds'in p?p.releaseIds:[]})
 const showRelated=(p:OnlinePlan)=>{reset();setRelated(p);setTab('experiment')}
 const copyExperiment=(e:AppExperiment)=>{const next=clone(e),v=clone(w.experiments[e.id]);next.id=makeId();next.name=`${e.name}（副本）`;next.status='DRAFT';next.startedAt='';next.endedAt='';next.salt=makeId();const plans:ExperimentPlans['plans']={};next.groups=next.groups.map(g=>{const id=makeId();plans[id]=clone(v.plans[g.id]??blankPlan());return {...g,id,bindings:[]}});open({kind:'experiment',value:next,visual:{...v,plans}})}
 const unit=store.versions.find(v=>v.id===unitPreview),unitDef=unit&&store.definitions.find(d=>d.id===unit.definitionId)
 return <div ref={root} className={`ab-page app-workbench ${editing?'ab-editing':''}`}>{holder}{modalHolder}
  <div className="ab-heading"><Space><Title level={3} style={{margin:0}}>APP A/B test配置</Title><Tag color="geekblue">五期</Tag></Space><Space>{editing?<><Button icon={<ArrowLeftOutlined/>} onClick={back}>返回列表</Button>{dirty&&<Text type="warning">未保存</Text>}{!locked&&<Button onClick={saveDraft}>保存草稿</Button>}</>:<Button onClick={()=>setArchive(true)}>旧版记录</Button>}</Space></div>
  <Alert type="info" showIcon className="ab-prototype-note" message="交互原型：配置、素材与发布记录仅保存在当前浏览器，暂不向真实 App 下发。"/>
  {!editing?<>
   <Tabs activeKey={tab} onChange={key=>{setTab(key);reset()}} items={[{key:'online',label:'线上配置'},{key:'experiment',label:'A/B 实验'}]}/>
   <div className="ab-list-intro"><div><Title level={4}>{tab==='online'?'线上配置':'A/B 实验'}</Title><Text type="secondary">{tab==='online'?'为不同国家、终端配置首次使用流程和页面；未参加实验的用户使用对应线上配置。':'选择线上方案作为起点，直接修改各组的流程、页面和素材，再比较效果。'}</Text></div><Button type="primary" icon={<PlusOutlined/>} disabled={!canEdit} onClick={()=>tab==='online'?open({kind:'online',value:newOnline()}):createExperiment(w.online.find(p=>p.status==='ACTIVE'))}>{tab==='online'?'新建线上配置':'新建实验'}</Button></div>
   <Card><Space wrap className="ab-list-filters"><Input.Search aria-label="搜索名称" placeholder="搜索名称" allowClear value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} style={{width:220}}/><Select aria-label="筛选国家" placeholder="全部国家" allowClear value={country} onChange={v=>{setCountry(v);setPage(1)}} options={countries.filter(c=>c.value!=='*')} style={{width:180}}/><Select aria-label="筛选终端" placeholder="全部终端" allowClear value={platform} onChange={v=>{setPlatform(v);setPage(1)}} options={['iOS','Android'].map(value=>({value,label:value}))} style={{width:130}}/><Select aria-label="筛选状态" placeholder="全部状态" allowClear value={status} onChange={v=>{setStatus(v);setPage(1)}} options={(tab==='online'?['DRAFT','ACTIVE','ENDED']:['DRAFT','READY','RUNNING','PAUSED','ENDED','TERMINATED']).map(value=>({value,label:statusLabels[value]}))} style={{width:130}}/><Button onClick={reset}>重置筛选</Button></Space>
    {related&&<div style={{marginBottom:16}}><Tag color="blue" closable onClose={()=>setRelated(null)}>关联线上配置：{related.name}</Tag></div>}
    {tab==='online'?<Table rowKey="id" dataSource={rows} pagination={{current:page,onChange:setPage,pageSize:8,showSizeChanger:false}} scroll={{x:1150}} columns={[
     {title:'配置名称',width:230,render:(_,p)=><><strong>{p.name||'未命名草稿'}</strong>{w.drafts.some(x=>x.id===p.id)&&<div><Tag color="orange">有未发布草稿</Tag></div>}</>},...scopeColumns,
     {title:'状态',width:100,render:(_,p)=><Tag color={statusColor(p.status)}>{statusLabels[p.status]}</Tag>},
     {title:'关联实验',width:100,render:(_,p)=><Button type="link" onClick={()=>showRelated(p)}>{relatedTo(store,p).length}</Button>},
     {title:'操作',width:300,fixed:'right',render:(_,p)=><Space wrap><Button type="link" onClick={()=>open({kind:'online',value:p},true)}>预览</Button>{canEdit&&<><Button type="link" onClick={()=>editOnline(p)}>{w.drafts.some(x=>x.id===p.id)?'继续编辑':'编辑'}</Button><Button type="link" onClick={()=>createExperiment(p)}>创建实验</Button></>}<Button type="link" onClick={()=>openHistory(p)}>编辑历史</Button>{canEdit&&p.status==='ACTIVE'&&<Button type="link" danger onClick={()=>modal.confirm({title:`结束「${p.name}」？`,content:'已有实验保留自己的页面快照，历史仍可查看。',onOk:()=>act(()=>persist(endOnline(store,p,actor)))})}>结束</Button>}</Space>}
    ]}/>:<Table rowKey="id" dataSource={experimentRows} pagination={{current:page,onChange:setPage,pageSize:8,showSizeChanger:false}} scroll={{x:1150}} locale={{emptyText:<Empty description="暂无实验，选择线上方案即可开始配置 A/B 组。"/>}} columns={[
     {title:'实验名称',width:210,render:(_,e)=><><strong>{e.name||'未命名实验'}</strong><div><Text type="secondary">基于：{w.experiments[e.id]?.baseName??'已有方案'}</Text></div></>},...scopeColumns,
     {title:'分组比例',width:140,render:(_,e)=>e.groups.map(g=>`${g.name} ${g.weight/100}%`).join(' / ')},{title:'状态',width:100,render:(_,e)=><Tag color={statusColor(e.status)}>{statusLabels[e.status]}</Tag>},
     {title:'操作',width:300,fixed:'right',render:(_,e)=><Space wrap><Button type="link" onClick={()=>open({kind:'experiment',value:e,visual:w.experiments[e.id]})}>{e.status==='DRAFT'&&canEdit?'编辑':'查看'}</Button><Button type="link" onClick={()=>openHistory(e)}>编辑历史</Button>{canEdit&&<><Button type="link" onClick={()=>copyExperiment(e)}>复制</Button>{e.status==='READY'&&<><Button type="link" onClick={()=>switchStatus(e,'DRAFT')}>退回草稿</Button><Button type="link" onClick={()=>switchStatus(e,'RUNNING')}>启动</Button></>}{e.status==='RUNNING'&&<Button type="link" onClick={()=>switchStatus(e,'PAUSED')}>暂停</Button>}{e.status==='PAUSED'&&<Button type="link" onClick={()=>switchStatus(e,'RUNNING')}>恢复</Button>}{['RUNNING','PAUSED'].includes(e.status)&&<><Button type="link" onClick={()=>switchStatus(e,'ENDED')}>结束</Button><Button type="link" danger onClick={()=>switchStatus(e,'TERMINATED')}>终止</Button></>}</>}</Space>}
    ]}/>}</Card>
  </>:<>
   <div className="ab-edit-meta"><Space><strong>{editing.value.name||(online?'新建线上配置':'新建实验')}</strong><Tag>{locked?'只读预览':'草稿'}</Tag></Space></div>
   <nav className="ab-step-nav"><Steps className="ab-steps" size="small" current={step} onChange={go} items={(online?['适用范围','流程与页面','检查并发布']:['实验设置','分组与页面','检查并就绪']).map(title=>({title}))}/></nav>
   {showErrors&&errors[step].length>0&&<Alert type="error" showIcon style={{marginBottom:16}} message={`本步骤有 ${errors[step].length} 项待修正`} description={<ul>{errors[step].map((e,i)=><li key={i}>{e}</li>)}</ul>}/>}
   {step===0?<div className="ab-settings-grid"><Card title={online?'线上配置信息':'实验设置'}><Form layout="vertical" disabled={locked}>
    <Form.Item label={online?'配置名称':'实验名称'} required><Input aria-label={online?'配置名称':'实验名称'} placeholder={online?'例如：沙特 Android 首次使用方案':'例如：首启注册流程对比'} value={editing.value.name} onChange={e=>online?updateOnline({name:e.target.value}):updateExperiment({name:e.target.value})}/></Form.Item>
    {exp&&visual&&<Form.Item label="基于哪个线上方案" extra="各组复制此刻的方案内容；之后的线上更新不会覆盖实验内容。"><Select aria-label="实验基准方案" disabled={locked} value={visual.baseId??'default'} options={[{value:'default',label:'默认方案'},...w.online.map(p=>({value:p.id,label:p.name}))]} onChange={id=>modal.confirm({title:'更换实验基准？',content:'各组已编辑的流程和页面将替换为所选方案；分组名称和比例保留。',onOk:()=>{const base=w.online.find(p=>p.id===id);updateExperiment({}, {baseId:base?.id,baseName:base?.name??'默认方案',baseMinVersion:base?.minVersion,plans:Object.fromEntries(exp.groups.map(g=>[g.id,clone(base?.plan??blankPlan())]))})}})}/></Form.Item>}
    <AudienceFields value={editing.value.audience} readOnly={locked} onChange={audience=>online?updateOnline({audience}):updateExperiment({audience})}/>
    <Form.Item label="最低 App 版本" required extra="该版本及以上可使用本方案；按 App 版本数值比较。"><Input aria-label="最低 App 版本" placeholder="例如 1.8.0" value={editing.value.minVersion} onChange={e=>online?updateOnline({minVersion:e.target.value.trim()}):updateExperiment({minVersion:e.target.value.trim()})}/></Form.Item>
    <div className="ab-target-summary"><strong>适用范围预览</strong><span>{countrySummary(audienceTarget(editing.value.audience))} · {platformSummary(audienceTarget(editing.value.audience))} · {editing.value.minVersion||'未填版本'} 及以上</span></div>
   </Form></Card><div className="ab-settings-aside"><Card title="操作顺序"><ol className="ab-instructions"><li>确定适用人群</li><li>{online?'选择流程，编辑页面与素材':'设置分组比例，分别编辑各组页面'}</li><li>{online?'预览检查后发布':'检查通过后启动实验'}</li></ol></Card><Card title={online?'谁会使用这套配置？':'实验如何保存？'}><Text>{online?'未参加有效实验的用户，按国家、终端和版本匹配线上配置。是否替换已有方案，在发布前确认。':'每组独立保存完整快照；后台自动管理版本，无需手工创建或绑定配置项。'}</Text></Card></div></div>:step===1?<>
    {online&&<ABVisualPlanEditor value={online.plan} onChange={plan=>updateOnline({plan})} readOnly={locked} target={audienceTarget(online.audience,online.minVersion)}/>}
    {exp&&visual&&<><Card title="实验分组" className="ab-group-table"><Space style={{marginBottom:16}}><Tag color={exp.groups.reduce((n,g)=>n+g.weight,0)===10000?'green':'red'}>合计 {exp.groups.reduce((n,g)=>n+g.weight,0)/100}%</Tag><Text type="secondary">各组占实验内流量的比例，合计须为 100%。</Text></Space>{exp.groups.map((g,i)=><div className="app-group-row" key={g.id}><Input aria-label={`分组 ${i+1} 名称`} disabled={locked} value={g.name} onChange={e=>updateExperiment({groups:exp.groups.map(x=>x.id===g.id?{...x,name:e.target.value}:x)})}/><InputNumber aria-label={`分组 ${i+1} 比例`} disabled={locked} min={0} max={100} precision={2} suffix="%" value={g.weight/100} onChange={n=>updateExperiment({groups:exp.groups.map(x=>x.id===g.id?{...x,weight:Math.round((n??0)*100)}:x)})}/><Radio disabled={locked} checked={g.control} onChange={()=>updateExperiment({groups:exp.groups.map(x=>({...x,control:x.id===g.id}))})}>对照组</Radio><Button aria-label={`删除分组 ${i+1}`} disabled={locked||exp.groups.length<=2} icon={<DeleteOutlined/>} onClick={()=>updateExperiment({groups:exp.groups.filter(x=>x.id!==g.id).map((x,n)=>g.control?{...x,control:n===0}:x)})}/></div>)}<Button disabled={locked} type="dashed" icon={<PlusOutlined/>} onClick={()=>{const id=makeId();updateExperiment({groups:[...exp.groups,{id,name:`分组 ${exp.groups.length+1}`,weight:0,control:false,bindings:[]}]},{...visual,plans:{...visual.plans,[id]:clone(visual.plans[exp.groups[0].id])}})}}>添加分组</Button></Card>
     <Tabs className="ab-group-tabs" activeKey={group?.id} onChange={setActiveGroup} items={exp.groups.map(g=>({key:g.id,label:`${g.name}${g.control?'（对照组）':''} · ${g.weight/100}%`}))}/>
     <Space style={{marginBottom:12}}>{locked&&canEdit&&group&&<Button onClick={()=>open({kind:'online',value:{...newOnline(),name:`${exp.name} · ${group.name} 转线上`,audience:clone(exp.audience),minVersion:exp.minVersion,plan:clone(visual.plans[group.id]??blankPlan())}})}>将此组发布为线上配置</Button>}</Space><Alert type="info" showIcon style={{marginBottom:16}} message={`当前编辑：${group?.name}。直接修改下方流程、文案与素材；其他分组不会变化。`}/>
     {group&&<ABVisualPlanEditor key={group.id} value={visual.plans[group.id]??blankPlan()} readOnly={locked} target={audienceTarget(exp.audience,exp.minVersion)} onChange={plan=>updateExperiment({}, {...visual,plans:{...visual.plans,[group.id]:plan}})}/>}</>}
   </>:<Card title={online?'检查并发布':'检查并就绪'}><Descriptions bordered column={2} items={[{key:'name',label:online?'配置名称':'实验名称',children:editing.value.name},{key:'min',label:'版本范围',children:`${editing.value.minVersion} 及以上`},{key:'country',label:'国家',children:countrySummary(audienceTarget(editing.value.audience))},{key:'platform',label:'终端',children:platformSummary(audienceTarget(editing.value.audience))},...(exp?[{key:'groups',label:'分组比例',children:exp.groups.map(g=>`${g.name} ${g.weight/100}%`).join(' / ')}]:[])]}/>
    {online&&!locked&&<Form layout="vertical" style={{marginTop:24,maxWidth:700}}><Form.Item label="发布方式" extra="保存草稿不会影响线上。发布成功后才替换；新建独立方案须通过范围冲突检查。"><Select aria-label="替换现有线上配置" value={online.replaceId??'new'} options={[{value:'new',label:'新建独立线上配置'},...w.online.map(p=>({value:p.id,label:`替换：${p.name}`}))]} onChange={id=>updateOnline({replaceId:id==='new'?undefined:id})}/></Form.Item></Form>}
    {publishError&&<Alert type="error" showIcon style={{marginTop:16}} message="暂时不能发布" description={publishError}/>}<Space wrap style={{margin:'20px 0'}}>{online?<Button onClick={()=>setSnapshot({kind:'online',value:online})}>预览完整方案</Button>:exp?.groups.map(g=><Button key={g.id} onClick={()=>{setActiveGroup(g.id);go(1)}}>预览 {g.name}</Button>)}</Space>
    <Alert type={errors[2].length?'error':'success'} showIcon message={errors[2].length?'仍有问题，不能提交':'本地检查通过'} description={errors[2].length?<ul>{errors[2].map((e,i)=><li key={i}>{e}</li>)}</ul>:online?'发布时再次检查适用范围冲突；发布内容将自动保留编辑历史。':'各组页面、流程和素材将保存为固定版本；设为就绪后，可在列表中启动实验。'}/>
   </Card>}
   <div className="ab-editor-actions" style={{left:footer.left,width:footer.width,visibility:footer.width?'visible':'hidden'}}><Button disabled={step===0} onClick={()=>go(step-1)}>上一步</Button><Space>{!locked&&errors[step].length>0&&<Button type="link" danger onClick={()=>setShowErrors(true)}>本步 {errors[step].length} 项待完善</Button>}{step<2?<Button type="primary" icon={<ArrowRightOutlined/>} onClick={()=>go(step+1)}>下一步：{step===0?(online?'配置流程与页面':'配置分组与页面'):'预览与检查'}</Button>:!locked&&<Button type="primary" onClick={finish}>{online?'发布线上配置':'设为就绪'}</Button>}</Space></div>
  </>}
  <Drawer width={1000} title={`编辑历史 · ${history?.name??''}`} open={!!history} onClose={()=>setHistory(null)}><Table rowKey="id" dataSource={w.history.filter(h=>h.entityId===history?.id||h.snapshot.kind==='online'&&h.snapshot.value.replaceId===history?.id).slice().reverse()} locale={{emptyText:'暂无整套方案的编辑记录；原有版本仍保留在下方。'}} columns={[{title:'时间',render:(_,h)=>formatDate(h.at)},{title:'操作人',dataIndex:'actor'},{title:'操作',dataIndex:'action'},{title:'操作',render:(_,h)=><Button onClick={()=>setSnapshot(h.snapshot)}>查看快照</Button>}]}/><Title level={5}>原有版本与操作记录</Title><Table rowKey="id" dataSource={store.audit.filter(a=>a.entityId===history?.id||history?.releaseIds.includes(a.entityId)||history?.versionIds.includes(a.entityId)).slice().reverse()} columns={[{title:'时间',render:(_,a)=>formatDate(a.at)},{title:'操作人',dataIndex:'actor'},{title:'操作',dataIndex:'action'},{title:'快照',render:(_,a)=>'content'in a.snapshot?<Button onClick={()=>setUnitPreview(a.entityId)}>查看页面内容</Button>:<Text>{'status'in a.snapshot?statusLabels[a.snapshot.status]:''}</Text>}]}/></Drawer>
  <Modal width="94vw" open={!!snapshot} onCancel={()=>setSnapshot(null)} footer={<Button onClick={()=>setSnapshot(null)}>关闭</Button>} title={`${snapshot?.value.name??''} · 快照预览`} styles={{body:{maxHeight:'78vh',overflowY:'auto'}}}>{snapshot?.kind==='online'?<ABVisualPlanEditor key={JSON.stringify(snapshot)} value={snapshot.value.plan} readOnly onChange={()=>{}} target={audienceTarget(snapshot.value.audience,snapshot.value.minVersion)}/>:snapshot?.kind==='experiment'?<Tabs items={snapshot.value.groups.map(g=>({key:g.id,label:g.name,children:<ABVisualPlanEditor value={snapshot.visual.plans[g.id]??blankPlan()} readOnly onChange={()=>{}} target={audienceTarget(snapshot.value.audience,snapshot.value.minVersion)}/>}))}/>:null}</Modal>
  <Modal width="94vw" open={!!unit&&!!unitDef} onCancel={()=>setUnitPreview(undefined)} footer={null} title="原有页面版本 · 只读" styles={{body:{maxHeight:'78vh',overflowY:'auto'}}}>{unit&&unitDef&&<ABUnitEditor slot={getSlot(unitDef.slotId)} content={unit.content} readOnly onChange={()=>{}} target={{countries:['*'],platforms:['iOS','Android'],versions:[{operator:'>=',value:unit.minVersion}]}}/>}</Modal>
  <Drawer width="90vw" title="旧版记录（只读）" open={archive} onClose={()=>setArchive(false)}><Title level={5}>已保存的页面版本</Title><Table rowKey="id" dataSource={store.versions.slice().reverse()} pagination={{pageSize:8}} columns={[{title:'配置名称',render:(_,v)=>store.definitions.find(d=>d.id===v.definitionId)?.name},{title:'版本',render:(_,v)=>`V${v.no}`},{title:'操作人',dataIndex:'actor'},{title:'保存时间',render:(_,v)=>formatDate(v.at)},{title:'操作',render:(_,v)=><Button onClick={()=>setUnitPreview(v.id)}>查看快照</Button>}]}/><Title level={5}>早期方案归档</Title><Table rowKey="id" dataSource={legacy.online} columns={[{title:'线上配置',dataIndex:'name'},{title:'操作',render:(_,x)=><Space><Button onClick={()=>setLegacyPreview({plan:x.plan,target:x.target,name:x.name})}>预览</Button><Button onClick={()=>setLegacyHistory({kind:'online',id:x.id,name:x.name})}>编辑历史</Button></Space>}]}/><Table rowKey="id" dataSource={legacy.experiments} columns={[{title:'实验名称',dataIndex:'name'},{title:'分组',render:(_,x)=><Space wrap>{x.variants.map(g=><Button key={g.id} onClick={()=>setLegacyPreview({plan:g.plan,target:x.target,name:`${x.name} / ${g.name}`})}>{g.name}</Button>)}<Button onClick={()=>setLegacyHistory({kind:'experiment',id:x.id,name:x.name})}>编辑历史</Button></Space>}]}/></Drawer>
  <Modal width="94vw" open={!!legacyPreview} onCancel={()=>setLegacyPreview(null)} footer={null} title={legacyPreview?.name} styles={{body:{maxHeight:'78vh',overflowY:'auto'}}}>{legacyPreview&&<ABPlanEditor plan={legacyPreview.plan} target={legacyPreview.target} readOnly onChange={()=>{}}/>}</Modal><ABHistoryDrawer store={legacy} subject={legacyHistory} onClose={()=>setLegacyHistory(null)}/>
 </div>
}
