import { useEffect, useRef, useState } from 'react'
import { Button, Input, Radio, Space, Upload, Typography } from 'antd'
import { putAsset, useAssetURL } from './ABAssetField'
import type { Asset } from '../abPageConfig'
export default function ABAudioField({value,onChange,disabled}:{value:Asset;onChange:(v:Asset)=>void;disabled:boolean}){
 const latest=useRef({onChange,disabled});latest.current={onChange,disabled};const active=useRef(true);useEffect(()=>{active.current=true;return()=>{active.current=false}},[])
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const {src}=useAssetURL(value)
 return <div className="ab-asset-field"><strong>引导语音</strong><Radio.Group disabled={disabled||busy} value={value.mode} onChange={e=>onChange({...value,mode:e.target.value})} options={[{value:'inherit',label:'沿用原语音'},{value:'custom',label:'替换语音'}]}/>{value.mode==='custom'&&<><Space.Compact style={{width:'100%',marginTop:10}}><Input aria-label="引导语音地址" disabled={disabled||busy} value={value.src?.startsWith('asset:')?'':value.src??''} placeholder="HTTPS 音频地址，或上传音频" onChange={e=>onChange({mode:'custom',src:e.target.value})}/><Upload disabled={disabled||busy} accept="audio/mpeg,audio/wav,audio/x-wav" showUploadList={false} beforeUpload={async file=>{setError('');setBusy(true);onChange({mode:'custom',src:''});try{if(!['audio/mpeg','audio/wav','audio/x-wav'].includes(file.type)||file.size>8*1024*1024)throw Error('原型支持 8 MB 内的 MP3 / WAV；正式规范待确认。');const id=crypto.randomUUID();await putAsset(id,file);if(active.current&&!latest.current.disabled)latest.current.onChange({mode:'custom',src:`asset:${id}`,name:file.name,mime:file.type,bytes:file.size})}catch(e){if(active.current)setError((e as Error).message)}finally{if(active.current)setBusy(false)}return false}}><Button loading={busy} disabled={disabled}>上传语音</Button></Upload></Space.Compact>{src&&<audio controls src={src} style={{width:'100%',marginTop:12}}/>}{value.name&&<Typography.Text type="secondary">{value.name}</Typography.Text>}</>}{error&&<div role="alert" style={{color:'#d4380d'}}>{error}</div>}</div>
}
