import { useState } from 'react'
import { Alert, Button, Card, Checkbox, Select, Space, Tag, Typography } from 'antd'
import { ArrowDownOutlined, ArrowUpOutlined, DeleteOutlined, PlusOutlined, ArrowRightOutlined } from '@ant-design/icons'
import { labels, makeId } from '../abTestConfig'
import { flowPages, simulateFlow, validateFlow } from '../appFlowConfig'
import type { FlowGraph, FlowNode } from '../appFlowConfig'
export default function ABFlowEditor({value,onChange,readOnly=false}:{value:FlowGraph;onChange:(g:FlowGraph)=>void;readOnly?:boolean}) {
 const [insertPage,setInsertPage]=useState('paywall'),[after,setAfter]=useState(''),[paid,setPaid]=useState(false),[outcomes,setOutcomes]=useState<Record<string,'success'|'failure'|'pending'>>({})
 const nodes=value.nodes,errors=validateFlow(value),trace=simulateFlow(value,outcomes,paid)
 const label=(id?:string)=>{const i=nodes.findIndex(n=>n.id===id);return i<0?'未设置':`${i+1}. ${labels[nodes[i].page]}`}
 const save=(next:FlowNode[])=>{if(!readOnly)onChange({...value,nodes:next,skipPaywallAfterSuccess:true})}
 const update=(id:string,p:Partial<FlowNode>)=>save(nodes.map(n=>n.id===id?{...n,...p}:n))
 const move=(i:number,delta:number)=>{const ns=[...nodes];[ns[i],ns[i+delta]]=[ns[i+delta],ns[i]];save(ns)}
 const remove=(i:number)=>{const target=nodes[i].id,next=nodes[i+1]?.id;if(after===target)setAfter('');save(nodes.filter(n=>n.id!==target).map(n=>({...n,...(n.successTo===target?{successTo:next}:{}),...(n.failureTo===target?{failureTo:next}:{})})))}
 const insert=()=>{const i=after?nodes.findIndex(n=>n.id===after):nodes.length-2;if(i<0)return;const next=nodes[i+1]?.id,id=makeId();const node:FlowNode={id,page:insertPage,...(insertPage==='paywall'?{successTo:next,failureTo:next}:{})};save(nodes.flatMap((n,index)=>index===i?[{...n,...(n.successTo===next?{successTo:id}:{}),...(n.failureTo===next?{failureTo:id}:{})},node]:[n]))}
 return <>
  <Alert type="info" showIcon message={value.standard==='REGISTER_FIRST'?'标准一：先注册，再体验':'标准二：先体验付费，再登录注册'} description="支付成功后，后续所有购买页自动跳过并走成功去向，不再弹出；支付结果确认中停留等待。课前支付成功可直接衔接登录；未支付成功的路径须继续体验。下方分别配置去向。" style={{marginBottom:16}}/>
  <div className="ab-flow-config-grid"><div>
   {nodes.map((n,i)=><Card key={n.id} size="small" className={`ab-flow-node ${n.page==='paywall'?'ab-flow-node-paywall':''}`} title={<Space><Tag>{i+1}</Tag><strong>{labels[n.page]}</strong>{n.page==='paywall'&&<Tag color="orange">支付分支</Tag>}{i===0&&<Tag>起点</Tag>}{n.page==='home'&&<Tag>终点</Tag>}</Space>} extra={<Space size={4}><Button aria-label={`上移节点 ${i+1}`} size="small" icon={<ArrowUpOutlined/>} disabled={readOnly||i<=1||n.page==='home'} onClick={()=>move(i,-1)}/><Button aria-label={`下移节点 ${i+1}`} size="small" icon={<ArrowDownOutlined/>} disabled={readOnly||i===0||i>=nodes.length-2} onClick={()=>move(i,1)}/><Button aria-label={`删除节点 ${i+1}`} size="small" danger icon={<DeleteOutlined/>} disabled={readOnly||i===0||['home','auth','lesson'].includes(n.page)} onClick={()=>remove(i)}/></Space>}>
    {n.page==='paywall'?<><div className="ab-flow-branch"><Tag color="green">支付成功</Tag><ArrowRightOutlined/><Select aria-label={`第 ${i+1} 步支付成功去向`} disabled={readOnly} value={n.successTo} placeholder="请选择后续节点" options={nodes.slice(i+1).map(x=>({value:x.id,label:label(x.id)}))} onChange={successTo=>update(n.id,{successTo})}/></div><div className="ab-flow-branch"><Tag color="orange">支付失败／取消</Tag><ArrowRightOutlined/><Select aria-label={`第 ${i+1} 步支付失败去向`} disabled={readOnly} value={n.failureTo} placeholder="请选择后续节点" options={nodes.slice(i+1).map(x=>({value:x.id,label:label(x.id)}))} onChange={failureTo=>update(n.id,{failureTo})}/></div><Typography.Text type="secondary">已支付用户：不展示本购买页，直接前往 {label(n.successTo)}。</Typography.Text></>:<Typography.Text type="secondary">{n.page==='home'?'流程结束':`完成后 → ${label(nodes[i+1]?.id)}`}</Typography.Text>}
   </Card>)}
   {!readOnly&&<Card size="small" title="添加页面节点"><Space wrap><Select aria-label="新增流程页面" value={insertPage} options={flowPages.filter(p=>!['auth','home','value'].includes(p)).map(value=>({value,label:labels[value]}))} onChange={setInsertPage} style={{width:150}}/><span>插入到</span><Select aria-label="插入位置" value={after||nodes[nodes.length-2]?.id} options={nodes.slice(0,-1).map(n=>({value:n.id,label:`${label(n.id)} 之后`}))} onChange={setAfter} style={{width:210}}/><Button icon={<PlusOutlined/>} onClick={insert}>添加节点</Button></Space></Card>}
  </div><Card className="ab-flow-simulator" title="路径预览"><Checkbox checked={paid} onChange={e=>setPaid(e.target.checked)}>进入流程前已经支付成功</Checkbox><Typography.Paragraph type="secondary" style={{marginTop:12}}>为每个购买页选择支付结果，查看实际会经过的页面。未到达的购买页不会执行。</Typography.Paragraph>{!paid&&nodes.filter(n=>n.page==='paywall').map(n=><div key={n.id} style={{margin:'12px 0'}}><strong>{label(n.id)}</strong><Select aria-label={`${label(n.id)}预览支付结果`} value={outcomes[n.id]??'failure'} options={[{value:'success',label:'支付成功'},{value:'failure',label:'支付失败／取消'},{value:'pending',label:'支付结果确认中'}]} style={{width:'100%',marginTop:8}} onChange={v=>setOutcomes({...outcomes,[n.id]:v})}/></div>)}
   {errors.length?<Alert type="error" message="先修正流程配置，再预览路径" description={<ul>{errors.map(e=><li key={e}>{e}</li>)}</ul>}/>:<ol className="ab-flow-trace">{trace.map(t=><li key={t.id} className={t.event==='skip-paid'?'is-skipped':''}><strong>{label(t.id)}</strong>{t.event==='success'&&<Tag color="green">支付成功</Tag>}{t.event==='failure'&&<Tag color="orange">支付失败／取消</Tag>}{t.event==='skip-paid'&&<Tag>已支付，跳过不展示</Tag>}{t.event==='waiting'&&<Tag color="blue">等待确认，不进入下一步</Tag>}</li>)}</ol>}
   <Typography.Text type="secondary">这是路径演示，不会发起真实支付。登录与课程等页面内部行为由 App 执行。</Typography.Text>
  </Card></div>
 </>
}
