import { useState } from 'react'
import { Alert, Button, Card, Form, Modal, Select, Space, Tag, Typography } from 'antd'
import { ArrowDownOutlined, ArrowUpOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import { labels, makeId } from '../abTestConfig'
import { simulateFlow, validateFlow, flowUnits, onboardingPages, isOnboardingPage, moveFlowUnit, sequential } from '../appFlowConfig'
import type { FlowGraph, FlowNode, Outcome } from '../appFlowConfig'
export default function ABFlowEditor({value,onChange,readOnly=false}:{value:FlowGraph;onChange:(g:FlowGraph)=>void;readOnly?:boolean}) {
 const [selected,setSelected]=useState(value.nodes[0]?.id),[adding,setAdding]=useState(false),[insertPage,setInsertPage]=useState('paywall'),[outcomes,setOutcomes]=useState<Record<string,Outcome>>({}),[owned,setOwned]=useState<false|'PRO'|'MAX'>(false)
 const units=flowUnits(value.nodes),index=Math.max(0,units.findIndex(u=>u.nodes.some(n=>n.id===selected))),unit=units[index],node=unit?.nodes[0],errors=validateFlow(value),trace=simulateFlow(value,outcomes,owned)
 const title=(n:FlowNode)=>isOnboardingPage(n.page)?'孩子资料填写（Onboarding）':labels[n.page]
 const save=(nodes:FlowNode[])=>{if(!readOnly)onChange({...value,nodes:sequential(nodes)})}
 const insert=()=>{const at=value.nodes.findIndex(n=>n.id===unit.nodes[unit.nodes.length-1].id),id=makeId();const added=insertPage==='onboarding'?onboardingPages.map(page=>({id:makeId(),page})):[{id,page:insertPage,...(insertPage==='paywall'?{configRef:id,entitlement:'PRO' as const}:{})}];save([...value.nodes.slice(0,at+1),...added,...value.nodes.slice(at+1)]);setAdding(false);setSelected(added[0].id)}
 return <div className="ab-flow-studio">
  <Alert type="info" showIcon message="按顺序执行，业务依赖在发布前校验" description="游客购买或恢复会员后须完成后置登录，再继续下一模块；无会员游客最终关闭购买页后可进入首页。支付取消、支付核验中和咨询/挽留处理中不会直接跳到下一模块。"/>
  {!!errors.length&&<Alert style={{marginTop:12}} type="error" showIcon message="当前流程不能发布" description={<ul>{errors.map(e=><li key={e}>{e}</li>)}</ul>}/>}
  <div className="ab-product-flow-grid"><Card title={<Space>模块顺序<Tag color={errors.length?'error':'success'}>{errors.length?'待修正':'依赖检查通过'}</Tag></Space>}>
   {units.map((u,i)=><div key={u.nodes[0].id} className="ab-product-flow-row"><Button block size="large" type={index===i?'primary':'default'} onClick={()=>setSelected(u.nodes[0].id)}>{String(i+1).padStart(2,'0')} · {title(u.nodes[0])}</Button>{u.onboarding&&<Typography.Text type="secondary">称呼 → 年龄 → 英语水平 → 学习目标</Typography.Text>}{u.nodes[0].page==='paywall'&&<Typography.Text type="secondary">{u.nodes[0].entitlement==='MAX'?'Max':'Pro'} 权益 · 独立页面内容</Typography.Text>}{i<units.length-1&&<div className="ab-product-flow-arrow">↓</div>}</div>)}
  </Card><div><Card title={node?title(node):'节点设置'}>
   {node&&<><p>{unit.onboarding?'内部四页顺序固定；可整体移动。':node.page==='home'?'流程终点。':'正常完成后进入下一个模块。'}</p>{node.page==='paywall'&&<><Form.Item label="本购买页对应权益"><Select aria-label="购买页对应权益" disabled={readOnly} value={node.entitlement??'PRO'} options={[{value:'PRO',label:'Pro 会员'},{value:'MAX',label:'Max 会员'}]} onChange={entitlement=>save(value.nodes.map(n=>n.id===node.id?{...n,entitlement}:n))}/></Form.Item><p>购买成功或恢复成功：会员游客先完成注册登录，再继续下一模块。最终关闭：完成咨询、挽留逻辑后继续。已有对应有效权益：跳过本购买页。</p><Typography.Text type="secondary">本节点的图文和商品在页面目录中独立配置；手机/Pad、普通/Promo 各自保存。</Typography.Text></>}
    {!readOnly&&<Space wrap style={{marginTop:18}}><Button icon={<ArrowUpOutlined/>} disabled={index<=1||node.page==='home'} onClick={()=>save(moveFlowUnit(value.nodes,index,-1))}>上移</Button><Button icon={<ArrowDownOutlined/>} disabled={index===0||index>=units.length-2} onClick={()=>save(moveFlowUnit(value.nodes,index,1))}>下移</Button><Button danger icon={<DeleteOutlined/>} disabled={index===0||unit.onboarding||node.page==='home'} onClick={()=>{save(value.nodes.filter(n=>!unit.nodes.some(x=>x.id===n.id)));setSelected(value.nodes[0].id)}}>删除</Button><Button icon={<PlusOutlined/>} disabled={node.page==='home'} onClick={()=>{setInsertPage('paywall');setAdding(true)}}>在此后添加</Button></Space>}
   </>}
  </Card><Card title="路径验证" style={{marginTop:16}}><Form.Item label="进入流程前的有效权益"><Select aria-label="预览已有权益" value={owned||'NONE'} options={[{value:'NONE',label:'无会员权益'},{value:'PRO',label:'Pro 会员'},{value:'MAX',label:'Max 会员'}]} onChange={v=>setOwned(v==='NONE'?false:v as 'PRO'|'MAX')}/></Form.Item>{value.nodes.filter(n=>n.page==='paywall').map((n,i)=><Form.Item key={n.id} label={`第 ${i+1} 次购买页`}><Select aria-label={`购买页 ${i+1} 预览结果`} value={outcomes[n.id]??'closed'} options={[{value:'success',label:'购买成功'},{value:'restore',label:'恢复购买成功'},{value:'closed',label:'最终关闭（咨询/挽留已结束）'},{value:'cancel',label:'取消支付，仍在购买页'},{value:'pending',label:'等待支付核验'}]} onChange={v=>setOutcomes({...outcomes,[n.id]:v})}/></Form.Item>)}<ol className="ab-simulation-trace">{trace.filter(t=>!isOnboardingPage(t.page)||t.page==='name').map(t=><li key={t.id}>{t.page==='name'?'Onboarding':labels[t.page]} <Tag>{({show:'展示',success:'获得权益',failure:'最终关闭',login:'会员游客强制登录',waiting:'等待核验',stay:'留在购买页','skip-paid':'已有对应权益，跳过'})[t.event]}</Tag></li>)}</ol></Card></div></div>
  <Modal title="添加流程模块" open={adding} onCancel={()=>setAdding(false)} onOk={insert} okText="添加"><Form.Item label="模块"><Select aria-label="新增流程页面" value={insertPage} onChange={setInsertPage} options={['teacher','lesson','report','plan','paywall',...(!value.nodes.some(n=>isOnboardingPage(n.page))?['onboarding']:[])].filter(p=>p==='paywall'||!value.nodes.some(n=>n.page===p)).map(value=>({value,label:value==='onboarding'?'资料采集（完整模块）':labels[value]}))}/></Form.Item><p>添加到当前选中模块之后；仅购买页可重复。</p></Modal>
 </div>
}
