import { useId, useRef, useState } from 'react'
import { Alert, Button, Checkbox, Form, Modal, Select, Space, Tabs, Tag, Tooltip, Typography } from 'antd'
import { ArrowDownOutlined, ArrowUpOutlined, DeleteOutlined, PlusOutlined, ArrowRightOutlined, CheckCircleOutlined, LockOutlined, MinusOutlined, ExpandOutlined, UndoOutlined, RedoOutlined, BranchesOutlined } from '@ant-design/icons'
import { labels, makeId, clone } from '../abTestConfig'
import { flowPages, simulateFlow, validateFlow, flowUnits, onboardingPages, isOnboardingPage, moveFlowUnit, onboardingErrors, restoreOnboarding } from '../appFlowConfig'
import type { FlowGraph, FlowNode } from '../appFlowConfig'
const diagramWidth=720,nodeLeft=180,nodeWidth=360,nodeHeight=68,rowHeight=100,topInset=24
export default function ABFlowEditor({value,onChange,readOnly=false}:{value:FlowGraph;onChange:(g:FlowGraph)=>void;readOnly?:boolean}) {
 const arrowId=useId().replace(/:/g,'')
 const nodes=value.nodes,units=flowUnits(nodes),errors=validateFlow(value)
 const [selected,setSelected]=useState(nodes.find(n=>n.page==='paywall')?.id??nodes[0]?.id),[panel,setPanel]=useState('settings'),[zoom,setZoom]=useState(1),[adding,setAdding]=useState(false)
 const [insertPage,setInsertPage]=useState('paywall'),[after,setAfter]=useState(''),[paid,setPaid]=useState(false),[outcomes,setOutcomes]=useState<Record<string,'success'|'failure'|'pending'>>({})
 const [past,setPast]=useState<FlowNode[][]>([]),[future,setFuture]=useState<FlowNode[][]>([]),viewport=useRef<HTMLDivElement>(null)
 const trace=simulateFlow(value,outcomes,paid),diagramHeight=units.length*rowHeight+topInset
 const index=Math.max(0,units.findIndex(u=>u.nodes.some(n=>n.id===selected))),unit=units[index],node=unit?.nodes[0]
 const unitIndex=(id?:string)=>units.findIndex(u=>u.nodes.some(n=>n.id===id))
 const unitName=(i:number)=>units[i]?.onboarding?'资料采集':labels[units[i]?.nodes[0].page]??'未设置'
 const label=(id?:string)=>{const i=unitIndex(id);return i<0?'未设置':`${String(i+1).padStart(2,'0')} ${unitName(i)}`}
 const apply=(next:FlowNode[])=>onChange({...value,nodes:clone(next),skipPaywallAfterSuccess:true})
 const save=(next:FlowNode[])=>{if(readOnly)return;setPast(p=>[...p.slice(-19),clone(nodes)]);setFuture([]);apply(next)}
 const undo=()=>{if(readOnly||!past.length)return;setFuture(f=>[clone(nodes),...f]);apply(past[past.length-1]);setPast(p=>p.slice(0,-1))}
 const redo=()=>{if(readOnly||!future.length)return;setPast(p=>[...p,clone(nodes)]);apply(future[0]);setFuture(f=>f.slice(1))}
 const update=(id:string,p:Partial<FlowNode>)=>save(nodes.map(n=>n.id===id?{...n,...p}:n))
 const remove=()=>{if(!unit)return;const ids=new Set(unit.nodes.map(n=>n.id)),next=units[index+1]?.nodes[0].id;setSelected(next??units[index-1]?.nodes[0].id);setAfter('');save(nodes.filter(n=>!ids.has(n.id)).map(n=>({...n,...(n.successTo&&ids.has(n.successTo)?{successTo:next}:{}),...(n.failureTo&&ids.has(n.failureTo)?{failureTo:next}:{})})))}
 const openAdd=()=>{setInsertPage('paywall');setAfter(units[index]?.nodes[0].page==='home'?units[units.length-2]?.nodes.slice(-1)[0].id:unit?.nodes.slice(-1)[0].id);setAdding(true)}
 const insert=()=>{const i=nodes.findIndex(n=>n.id===after);if(i<0||i>=nodes.length-1)return;const next=nodes[i+1]?.id,added:FlowNode[]=insertPage==='onboarding'?onboardingPages.map(page=>({id:makeId(),page})):[{id:makeId(),page:insertPage,...(insertPage==='paywall'?{successTo:next,failureTo:next}:{})}];save(nodes.flatMap((n,j)=>j===i?[{...n,...(n.successTo===next?{successTo:added[0].id}:{}),...(n.failureTo===next?{failureTo:added[0].id}:{})},...added]:[n]));setSelected(added[0].id);setPanel('settings');setAdding(false)}
 const fit=()=>{const el=viewport.current;if(el)setZoom(Math.max(.5,Math.min(1.2,(el.clientWidth-40)/diagramWidth,(el.clientHeight-40)/diagramHeight)))}
 const locate=(id:string)=>{setSelected(id);const i=unitIndex(id);if(viewport.current&&i>=0)viewport.current.scrollTo({top:Math.max(0,(topInset+i*rowHeight)*zoom-viewport.current.clientHeight/2+80),behavior:'smooth'})}
 const visibleTrace=trace.filter(t=>!isOnboardingPage(t.page)||t.page==='name')
 const previewMode=panel==='preview',traceById=new Map(trace.map(t=>[t.id,t])),firstPaywall=nodes.find(n=>n.page==='paywall')
 const branchOptions=units.slice(index+1).map(u=>({value:u.nodes[0].id,label:label(u.nodes[0].id)}))
 const canDelete=!!node&&index>0&&!['home','auth','lesson'].includes(node.page)
 const settings=<div className="ab-flow-inspector-content">{node&&<>
  <div className="ab-inspector-title"><span className="ab-node-number">{String(index+1).padStart(2,'0')}</span><div><h3>{unitName(index)}</h3><span>{node.page==='paywall'?'按支付结果选择后续路径':unit.onboarding?'四个页面作为一个完整模块':'按顺序进入下一个模块'}</span></div></div>
  {unit.onboarding?<div className="ab-inspector-block"><div className="ab-inspector-label"><LockOutlined/> 内部顺序固定</div><ol className="ab-fixed-module-list">{unit.nodes.map(n=><li key={n.id}>{labels[n.page]}</li>)}</ol><p>可以整体移动，内部页面不可拆分、排序或插入其他节点。</p></div>:node.page==='paywall'?<>
   <Form layout="vertical" className="ab-branch-form"><Form.Item label={<span className="ab-branch-success">● 支付成功</span>}><Select aria-label={`第 ${index+1} 步支付成功去向`} disabled={readOnly} value={node.successTo} placeholder="选择后续节点" options={branchOptions} onChange={successTo=>update(node.id,{successTo})}/></Form.Item><Form.Item label={<span className="ab-branch-failure">● 支付失败／取消</span>}><Select aria-label={`第 ${index+1} 步支付失败去向`} disabled={readOnly} value={node.failureTo} placeholder="选择后续节点" options={branchOptions} onChange={failureTo=>update(node.id,{failureTo})}/></Form.Item></Form>
   <div className="ab-payment-policy"><LockOutlined/><div><strong>支付成功后不再展示购买页</strong><p>进入本节点时若已支付，自动跳过并前往 {label(node.successTo)}。支付结果确认中保持等待。</p></div></div>
  </>:<div className="ab-next-destination"><span>{node.page==='home'?'流程终点':'完成后进入'}</span><strong>{node.page==='home'?'首页':label(units[index+1]?.nodes[0].id)}</strong></div>}
  {!readOnly&&<div className="ab-inspector-actions"><div className="ab-inspector-label">调整流程位置</div><Space><Button icon={<ArrowUpOutlined/>} disabled={index<=1||node.page==='home'} onClick={()=>save(moveFlowUnit(nodes,index,-1))}>上移</Button><Button icon={<ArrowDownOutlined/>} disabled={index===0||index>=units.length-2} onClick={()=>save(moveFlowUnit(nodes,index,1))}>下移</Button><Button aria-label="删除当前节点" danger icon={<DeleteOutlined/>} disabled={!canDelete} onClick={remove}/></Space>{!canDelete&&<p>起点、注册登录、体验课与终点为必要节点。</p>}<Button block type="dashed" icon={<PlusOutlined/>} style={{marginTop:14}} onClick={openAdd}>在此后添加节点</Button></div>}
  <Button block onClick={()=>setPanel('preview')} style={{marginTop:20}}>验证实际经过的路径 <ArrowRightOutlined/></Button>
 </>}</div>
 const preview=<div className="ab-flow-inspector-content"><div className="ab-preview-section-label">选择演示场景</div><Space wrap className="ab-scenario-buttons"><Button size="small" onClick={()=>{setPaid(false);setOutcomes({})}}>均未支付</Button><Button size="small" disabled={!firstPaywall} onClick={()=>{setPaid(false);setOutcomes({[firstPaywall!.id]:'success'})}}>首次支付成功</Button><Button size="small" onClick={()=>setPaid(true)}>进入前已支付</Button></Space><Checkbox checked={paid} onChange={e=>setPaid(e.target.checked)}>进入流程前已经支付成功</Checkbox>
  {!paid&&nodes.filter(n=>n.page==='paywall').map(n=><div key={n.id} className="ab-payment-outcome"><label>{label(n.id)}</label><Select aria-label={`${label(n.id)}预览支付结果`} value={outcomes[n.id]??'failure'} options={[{value:'success',label:'支付成功'},{value:'failure',label:'支付失败／取消'},{value:'pending',label:'支付结果确认中'}]} onChange={v=>setOutcomes({...outcomes,[n.id]:v})}/></div>)}
  {errors.length?<Alert type="error" showIcon message="请先修正流程配置" description="当前流程无有效演示路径，问题已列在画布上方。"/>:<><div className="ab-trace-summary"><strong>实际展示 {visibleTrace.filter(t=>t.event!=='skip-paid').length} 个模块</strong><span>跳过 {visibleTrace.filter(t=>t.event==='skip-paid').length} 个购买页</span></div><ol className="ab-simulation-trace">{visibleTrace.map(t=><li key={t.id} className={t.event==='skip-paid'?'is-skipped':''}><button onClick={()=>locate(t.id)}>{label(t.id)}</button>{t.event==='success'?<span className="ab-branch-success">支付成功</span>:t.event==='failure'?<span className="ab-branch-failure">失败／取消</span>:t.event==='skip-paid'?<span>已支付 · 跳过</span>:t.event==='waiting'?<span className="ab-branch-failure">等待确认</span>:null}</li>)}</ol></>}
  <p className="ab-simulator-note">仅演示配置路径，不发起真实支付；点击路径节点可定位到流程图。</p>
 </div>
 return <div className="ab-flow-studio">
  <div className="ab-flow-studio-toolbar"><div><strong>{value.standard==='REGISTER_FIRST'?'先注册，再体验':'先体验付费，再登录注册'}</strong><span>{units.length} 个模块 · {nodes.filter(n=>n.page==='paywall').length} 个购买页</span></div><Space><Tag icon={errors.length?undefined:<CheckCircleOutlined/>} color={errors.length?'error':'success'}>{errors.length?`${errors.length} 项待修正`:'流程检查通过'}</Tag>{!readOnly&&<><Tooltip title="撤销上一步"><Button aria-label="撤销流程修改" icon={<UndoOutlined/>} disabled={!past.length} onClick={undo}/></Tooltip><Tooltip title="重做"><Button aria-label="重做流程修改" icon={<RedoOutlined/>} disabled={!future.length} onClick={redo}/></Tooltip><Button type="primary" icon={<PlusOutlined/>} onClick={openAdd}>添加节点</Button></>}</Space></div>
  {!!errors.length&&<Alert className="ab-flow-studio-errors" type="error" showIcon message="请修正流程后再提交" description={<ul>{errors.map(e=><li key={e}>{e}</li>)}</ul>} action={!readOnly&&onboardingErrors(nodes).length?<Button size="small" onClick={()=>save(restoreOnboarding(nodes,makeId))}>恢复模块固定顺序</Button>:undefined}/>}
  <div className="ab-flow-studio-grid"><section className="ab-flow-canvas" aria-label="流程总览"><div className="ab-canvas-heading"><div><strong>流程总览</strong><span>{previewMode?'画布显示当前演示路径':'点击节点，在右侧设置顺序和分支'}</span></div><Space size={4}><Button aria-label="缩小流程图" size="small" type="text" icon={<MinusOutlined/>} disabled={zoom<=.5} onClick={()=>setZoom(z=>Math.max(.5,z-.1))}/><span className="ab-zoom-value">{Math.round(zoom*100)}%</span><Button aria-label="放大流程图" size="small" type="text" icon={<PlusOutlined/>} disabled={zoom>=1.3} onClick={()=>setZoom(z=>Math.min(1.3,z+.1))}/><Tooltip title="适应画布"><Button aria-label="适应画布" size="small" type="text" icon={<ExpandOutlined/>} onClick={fit}/></Tooltip></Space></div>
   <div className="ab-canvas-viewport" ref={viewport}><div className="ab-diagram-size" style={{width:diagramWidth*zoom,height:diagramHeight*zoom}}><div className="ab-flow-diagram" style={{width:diagramWidth,height:diagramHeight,transform:`scale(${zoom})`}}>
    <svg className="ab-flow-connections" width={diagramWidth} height={diagramHeight} aria-hidden="true"><defs>{['normal','success','failure'].map((type,i)=><marker key={type} id={`${arrowId}-arrow-${type}`} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M 0 0 L 7 3.5 L 0 7 Z" fill={['#b9c5d5','#39a778','#e2a040'][i]}/></marker>)}</defs>{units.flatMap((u,i)=>{const n=u.nodes[0],y=topInset+i*rowHeight,entry=traceById.get(n.id);if(n.page==='paywall')return (['success','failure'] as const).map((type)=>{const target=unitIndex(type==='success'?n.successTo:n.failureTo);if(target<=i)return null;const left=type==='success',x=left?nodeLeft:nodeLeft+nodeWidth,lane=left?64-(i%3)*12:diagramWidth-64+(i%3)*12,ty=topInset+target*rowHeight+nodeHeight/2,active=entry&&(type==='success'?['success','skip-paid'].includes(entry.event):entry.event==='failure');return <path key={`${n.id}-${type}`} d={`M ${x} ${y+nodeHeight/2} H ${lane} V ${ty} H ${x}`} fill="none" stroke={left?'#39a778':'#e2a040'} strokeWidth={previewMode&&active?3:1.6} opacity={previewMode&&!active?0.13:1} markerEnd={`url(#${arrowId}-arrow-${type})`}/>});if(i===units.length-1)return [];return [<path key={n.id} d={`M ${diagramWidth/2} ${y+nodeHeight} V ${y+rowHeight}`} stroke="#b9c5d5" strokeWidth="1.5" fill="none" opacity={previewMode&&!entry?0.15:1} markerEnd={`url(#${arrowId}-arrow-normal)`}/>]})}</svg>
    {units.map((u,i)=>{const n=u.nodes[0],entry=traceById.get(n.id),skipped=entry?.event==='skip-paid',dim=previewMode&&(!entry||skipped);return <button type="button" key={n.id} aria-label={`选择节点 ${i+1} ${unitName(i)}`} aria-pressed={index===i} className={`ab-diagram-node ${n.page==='paywall'?'is-paywall':''} ${index===i?'is-selected':''} ${dim?'is-dimmed':''} ${skipped?'is-skipped':''}`} style={{left:nodeLeft,top:topInset+i*rowHeight,width:nodeWidth,height:nodeHeight}} onClick={()=>{setSelected(n.id);if(!previewMode)setPanel('settings')}}><span className="ab-node-number">{String(i+1).padStart(2,'0')}</span><span className="ab-diagram-node-copy"><strong>{unitName(i)}</strong><small>{u.onboarding?'称呼 → 年龄 → 英语水平 → 学习目标':n.page==='paywall'?`成功 → ${label(n.successTo)}　失败 → ${label(n.failureTo)}`:i===0?'起点 · 开始首次使用流程':n.page==='home'?'终点 · 完成首次使用流程':`完成后 → ${label(units[i+1]?.nodes[0].id)}`}</small></span>{u.onboarding?<LockOutlined/>:n.page==='paywall'?<BranchesOutlined/>:null}{previewMode&&entry&&<span className={`ab-canvas-result result-${entry.event}`}>{({success:'成功',failure:'失败',waiting:'等待', 'skip-paid':'跳过',show:'经过'})[entry.event]}</span>}</button>})}
   </div></div></div><div className="ab-canvas-legend"><span><i className="success"/>支付成功／已支付</span><span><i className="failure"/>支付失败／取消</span><span><LockOutlined/> 资料采集内部顺序固定</span></div>
  </section><aside className="ab-flow-inspector"><Tabs activeKey={panel} onChange={setPanel} items={[{key:'settings',label:'节点设置',children:settings},{key:'preview',label:'路径验证',children:preview}]}/></aside></div>
  <Modal title="添加流程节点" open={adding} onCancel={()=>setAdding(false)} onOk={insert} okText="添加到流程" okButtonProps={{disabled:readOnly||!after}}><Form layout="vertical" style={{marginTop:20}}><Form.Item label="页面或模块"><Select aria-label="新增流程页面" value={insertPage} options={[...flowPages.filter(p=>!['auth','home','value'].includes(p)&&!isOnboardingPage(p)).map(value=>({value,label:labels[value]})),...(!nodes.some(n=>isOnboardingPage(n.page))?[{value:'onboarding',label:'资料采集（完整模块）'}]:[])]} onChange={setInsertPage}/></Form.Item><Form.Item label="插入位置"><Select aria-label="插入位置" value={after} options={units.slice(0,-1).map(u=>({value:u.nodes.slice(-1)[0].id,label:`${label(u.nodes[0].id)} 之后`}))} onChange={setAfter}/></Form.Item><Typography.Text type="secondary">添加后可继续设置分支或调整位置；资料采集内部不支持插入。</Typography.Text></Form></Modal>
 </div>
}
