import { useState } from 'react'
import { Button, Card, Checkbox, Form, Input, InputNumber, Radio, Select, Space, Tabs, Typography } from 'antd'
import { ArrowUpOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import ABAssetField, { AssetPreview } from './ABAssetField'
import { defaultMembers } from '../appConfigModel'
import type { Member } from '../appConfigModel'
export default function ABMemberEditor({value,onChange,readOnly,language,text,onText}:{value:Member[];onChange:(v:Member[])=>void;readOnly:boolean;language:string;text:(key:string,base:string)=>string;onText:(key:string,value:string)=>void}){
 const [active,setActive]=useState(value[0]?.id??1);const member=value.find(m=>m.id===active)??value[0];const locked=readOnly||language!=='zh'
 const change=(patch:Partial<Member>)=>onChange(value.map(m=>m.id===member.id?{...m,...patch}:m))
 const field=(key:string,base:string,update:(v:string)=>void)=><Input aria-label={key} value={text(key,base)} disabled={readOnly} onChange={e=>language==='zh'?update(e.target.value):onText(key,e.target.value)}/>
 return <><Space wrap style={{marginBottom:16}}><strong>配置会员档位</strong>{[1,2].map(id=><Checkbox key={id} disabled={locked} checked={value.some(m=>m.id===id)} onChange={e=>{const next=e.target.checked?[...value,defaultMembers().find(m=>m.id===id)!]:value.filter(m=>m.id!==id);onChange(next);setActive(next[0]?.id??1)}}>{id===1?'Pro':'Max'}</Checkbox>)}</Space>{!member?<Typography.Text type="danger">至少选择一个会员档位</Typography.Text>:<><Tabs activeKey={String(member.id)} onChange={id=>setActive(Number(id))} items={value.map(m=>({key:String(m.id),label:m.id===1?'Pro 会员':'Max 会员'}))}/><div className="ab-editor-grid"><Card title="权益内容与订阅周期"><Form layout="vertical" disabled={locked}><Form.Item label="内容资源"><Radio.Group value={member.mode} onChange={e=>change({mode:e.target.value})} options={[{value:'table',label:'权益对比表'},{value:'asset',label:'图片 / GIF'}]}/></Form.Item></Form>{member.mode==='asset'?<ABAssetField label="档位宣传资源" allowGif allowHide={false} value={member.asset} disabled={locked} onChange={asset=>change({asset})}/>:<><div className="ab-two-fields">{member.columns.map((col,i)=><Form.Item label={`第 ${i+1} 列标题`} key={col.id}>{field(`member.${member.id}.column.${col.id}`,col.label,label=>change({columns:member.columns.map(c=>c.id===col.id?{...c,label}:c)}))}<Button size="small" disabled={locked||i===0} onClick={()=>{const cols=[...member.columns];[cols[i-1],cols[i]]=[cols[i],cols[i-1]];change({columns:cols})}}>上移列</Button></Form.Item>)}</div>{member.rows.map((row,i)=><div className="ab-repeat-item" key={row.id}><Space style={{width:'100%',justifyContent:'space-between'}}><strong>权益 {i+1}</strong><Space><Button aria-label={`上移权益 ${i+1}`} disabled={locked||i===0} icon={<ArrowUpOutlined/>} onClick={()=>{const rows=[...member.rows];[rows[i-1],rows[i]]=[rows[i],rows[i-1]];change({rows})}}/><Button aria-label={`删除权益 ${i+1}`} disabled={locked} icon={<DeleteOutlined/>} onClick={()=>change({rows:member.rows.filter(x=>x.id!==row.id)})}/></Space></Space>{field(`member.${member.id}.row.${row.id}`,row.label,label=>change({rows:member.rows.map(x=>x.id===row.id?{...x,label}:x)}))}<Space style={{marginTop:12}}>{member.columns.map(col=><Checkbox key={col.id} disabled={locked} checked={row.values[col.id]} onChange={e=>change({rows:member.rows.map(x=>x.id===row.id?{...x,values:{...x.values,[col.id]:e.target.checked}}:x)})}>{col.label} 包含</Checkbox>)}</Space></div>)}<Button block disabled={locked} icon={<PlusOutlined/>} onClick={()=>change({rows:[...member.rows,{id:crypto.randomUUID(),label:'',values:Object.fromEntries(member.columns.map(c=>[c.id,false]))}]})}>添加权益行</Button></>}
 <Typography.Title level={5}>订阅周期</Typography.Title><Select mode="multiple" aria-label="订阅周期" disabled={locked} style={{width:'100%'}} value={member.cycles.map(c=>c.id)} options={[{value:'MONTH',label:'月度'},{value:'YEAR',label:'年度'}]} onChange={ids=>change({cycles:ids.map(id=>member.cycles.find(c=>c.id===id)??{id,label:id==='MONTH'?'月度':'年度',priceSize:16,priceColor:'#27344a',original:false})})}/>{member.cycles.map(c=><div className="ab-repeat-item" key={c.id}><Form.Item label={c.id==='MONTH'?'月度显示名称':'年度显示名称'}>{field(`member.${member.id}.cycle.${c.id}`,c.label,label=>change({cycles:member.cycles.map(x=>x.id===c.id?{...x,label}:x)}))}</Form.Item><Space wrap><span>价格字号</span><InputNumber aria-label={`${c.id}价格字号`} disabled={locked} min={1} value={c.priceSize} onChange={n=>change({cycles:member.cycles.map(x=>x.id===c.id?{...x,priceSize:n??0}:x)})}/><Input aria-label={`${c.id}价格颜色`} type="color" disabled={locked} style={{width:60}} value={c.priceColor} onChange={e=>change({cycles:member.cycles.map(x=>x.id===c.id?{...x,priceColor:e.target.value}:x)})}/><Checkbox disabled={locked} checked={c.original} onChange={e=>change({cycles:member.cycles.map(x=>x.id===c.id?{...x,original:e.target.checked}:x)})}>有有效原价时展示</Checkbox></Space></div>)}<Typography.Text type="secondary">售价来自商店；这里只设置周期展示与价格样式。</Typography.Text></Card>
 <div className="ab-preview-panel"><strong>会员档位预览</strong><div className="ab-phone" style={{marginTop:20,padding:22,height:'auto',minHeight:540}}><h2>Dino {member.id===1?'Pro':'Max'}</h2>{member.mode==='asset'?<AssetPreview asset={member.asset} label="会员档位资源"/>:<table className="ab-benefit-table"><thead><tr><th>权益</th>{member.columns.map(c=><th key={c.id}>{text(`member.${member.id}.column.${c.id}`,c.label)}</th>)}</tr></thead><tbody>{member.rows.map(row=><tr key={row.id}><td>{text(`member.${member.id}.row.${row.id}`,row.label)}</td>{member.columns.map(c=><td key={c.id}>{row.values[c.id]?'✓':'—'}</td>)}</tr>)}</tbody></table>}{member.cycles.map(c=><div className="ab-store-product" key={c.id}><b>{text(`member.${member.id}.cycle.${c.id}`,c.label)}</b><span style={{fontSize:c.priceSize,color:c.priceColor}}>商店本地价格</span>{c.original&&<del>有效原价（示意）</del>}</div>)}<div className="ab-preview-button">购买按钮沿用对应配置</div></div></div></div></>}</>
}
