import { useState } from 'react'
import { Alert, Button, Card, Collapse, Space, Tag, Typography, Select } from 'antd'
import { ArrowRightOutlined, CheckOutlined, MobileOutlined } from '@ant-design/icons'
import { templates, labels, languages, isEditableNode } from '../abTestConfig'
import type { Plan, Target } from '../abTestConfig'
import ABPageEditor from './ABPageEditor'
const { Text, Title, Paragraph } = Typography
const flowRules: Record<string, string[]> = {
 'register-first': ['注册成功 → 资料与定级 → 选老师 → 体验课 → 完课报告 → 学习计划 → 主购买页 → 首页。', '有效会员跳过购买页；购买成功或完成最终关闭处理后进入首页。'],
 'experience-first': ['首启价值页的新用户入口 → 资料与定级 → 选老师 → 体验课 → 完课报告 → 学习计划 → 主购买页。', '支付成功、明确失败、取消支付或最终关闭购买页后，未登录用户先注册登录，再进入首页；已登录直接进入首页。支付结果未确定时继续核实。', '首启页“已有账号”入口直接注册登录；绑定新账号后按资料继续未完成步骤，切换旧账号则使用旧账号的数据与配置。'],
 'double-paywall': ['首启价值页 → 资料与定级 → 学习计划 → 课前购买页 → 选老师 → 体验课 → 完课报告 → 课后购买页 → 注册登录 → 首页。', '任一购买页点击购买且未登录时先登录；绑定新账号后回原购买位置，保留所选商品并重新检查可售性。', '课前购买页结束后进入选老师和体验课；课后购买页结束时，未登录先登录，已登录直接进入首页。前一次看过或关闭购买页不跳过后面的购买页。'],
}
export default function ABPlanEditor({plan,onChange,readOnly=false,basePlan,target}:{plan:Plan;onChange:(plan:Plan)=>void;readOnly?:boolean;basePlan?:Plan;target:Target}) {
 const [node,setNode]=useState(()=>(templates.find(t=>t.id===plan.template)??templates[0]).nodes[0]);const [language,setLanguage]=useState('zh')
 const template=templates.find(t=>t.id===plan.template)??templates[0]
 return <div className="ab-plan-editor"><div className="ab-plan-toolbar"><Space wrap><strong>流程与页面</strong>{readOnly&&<Tag>只读预览</Tag>}{basePlan&&<Tag color={JSON.stringify(basePlan)===JSON.stringify(plan)?'default':'blue'}>{JSON.stringify(basePlan)===JSON.stringify(plan)?'与基准快照一致':'已独立修改'}</Tag>}</Space><Select aria-label="预览语言" value={language} onChange={setLanguage} options={languages} style={{width:185}}/></div><section className="ab-section"><div className="ab-section-title"><h3>选择流程模板</h3><Text type="secondary">三套首期方案</Text></div><div className="ab-template-grid">{templates.map(t=><button disabled={readOnly} aria-pressed={t.id===plan.template} key={t.id} className={`ab-template ${t.id===plan.template?'is-active':''}`} onClick={()=>{if(!readOnly){onChange({...plan,template:t.id});setNode(t.nodes[0])}}}><div><span>{t.badge}</span>{t.id===plan.template&&<CheckOutlined/>}</div><h3>{t.name}</h3><p>{t.desc}</p></button>)}</div></section><Card className="ab-flow-card" size="small" title="流程与页面入口" extra={<Text type="secondary">点击节点编辑对应页面</Text>}><div className="ab-flow">{template.nodes.map((key,i)=><div className="ab-flow-item" key={key}><button className={node===key?'selected':''} onClick={()=>setNode(key)}><span>{String(i+1).padStart(2,'0')}</span>{labels[key]}{isEditableNode(key)&&<i/>}</button>{i<template.nodes.length-1&&<ArrowRightOutlined/>}</div>)}</div><div className="ab-retention-entry"><Text type="secondary">购买页退出场景</Text><Button size="small" type={node==='retention-promo'?'primary':'default'} onClick={()=>setNode('retention-promo')}>挽留支付 · Promo</Button><Button size="small" type={node==='retention-regular'?'primary':'default'} onClick={()=>setNode('retention-regular')}>挽留支付 · 普通</Button><Text type="secondary">两套场景独立保存，切换场景不改变实验分组</Text></div><Collapse ghost size="small" items={[{key:'rules',label:'查看本方案的出口、登录及跳过规则',children:<><ul className="ab-flow-rules">{flowRules[plan.template]?.map(rule=><li key={rule}>{rule}</li>)}<li>“最终关闭”包含预约人工咨询、挽留支付等现有退出处理。取消或登录失败保留进度，不继续下一步。</li><li>已登录、资料与定级完整、已选老师等按业务状态跳过。选老师与学习计划依赖资料及定级，体验课依赖老师与体验资格，完课报告依赖对应课程完成。</li></ul><Text type="secondary">本原型使用 PRD 三套模板；自由组装、出口编辑及依赖校验仍待流程协议确认，尚未提供。</Text></>}]} /></Card>{isEditableNode(node)?<ABPageEditor key={node} plan={plan} node={node} language={language} target={target} readOnly={readOnly} onChange={onChange}/>:<Card><div className="ab-fixed"><MobileOutlined/><Title level={4}>{labels[node]}</Title><Paragraph type="secondary">该模块沿用 App 现有业务页面。PRD 本期没有列出可替换的页面元素，保留其流程位置与前后依赖。</Paragraph></div></Card>}<Alert className="ab-inline-note" type="info" message="当前编辑的是此方案的独立内容；图片、选项、商品、译文与流程随实验一起冻结，转线上时一并复制。"/></div>
}
