import ABTrialLessonEditor from './ABTrialLessonEditor'
import { useState } from 'react'
import { Alert, Button, Card, Drawer, Empty, Select, Space, Typography } from 'antd'
import { labels } from '../abTestConfig'
import type { Target } from '../abTestConfig'
import { appPlan, contentPlan, extractContent, scopeOf, validateContent } from '../appConfigModel'
import { effectiveContent, pageSlots } from '../appBusinessConfig'
import type { VisualPlan } from '../appBusinessConfig'
import ABTranslationReview from './ABTranslationReview'
import ABPageEditor from './ABPageEditor'
import ABMemberEditor from './ABMemberEditor'
import ABFlowEditor from './ABFlowEditor'
import { flowStandards, flowUnits } from '../appFlowConfig'
import { productLanguages } from '../appProductCopy'
export default function ABVisualPlanEditor({value,onChange,readOnly=false,target,editableScopes}:{value:VisualPlan;onChange:(p:VisualPlan)=>void;readOnly?:boolean;target:Target;editableScopes?:string[]}) {
 const [selected,setSelected]=useState({page:'auth',ref:''}),[language,setLanguage]=useState('en'),[member,setMember]=useState(false),[flowOpen,setFlowOpen]=useState(false),[translationsOpen,setTranslationsOpen]=useState(false),[device,setDevice]=useState('phone'),[scene,setScene]=useState('regular')
 const flowContent=effectiveContent(value,value.flowId),graph=flowContent.flow!,units=flowUnits(graph.nodes)
 const isLesson=selected.page==='lesson',isPaywall=selected.page==='paywall',node=isPaywall?`paywall-${device}-${scene}`:selected.page,slots=pageSlots(value,node,selected.ref||undefined)
 const plan=slots.reduce((p,s)=>contentPlan(effectiveContent(value,s.id),s,p),appPlan(node))
 const pageLocked=readOnly||!!editableScopes&&!editableScopes.includes(isPaywall?'paywall':selected.page),flowLocked=readOnly||!!editableScopes&&!editableScopes.includes('flow')
 const update=(contents:VisualPlan['contents'])=>{if(!readOnly)onChange({...value,contents:{...value.contents,...Object.fromEntries(Object.entries(contents).map(([id,c])=>[id,{translationSource:effectiveContent(value,id).translationSource,...c}]))}})}
 const issues=slots.flatMap(s=>validateContent(s,effectiveContent(value,s.id)))
 const pick=(page:string,ref='')=>{setSelected({page,ref});setMember(false)}
 const title=(page:string)=>labels[page]??page
 const pageButton=(page:string,ref='',index?:number)=><button type="button" className={`ab-nav-page ${selected.page===page&&selected.ref===ref?'is-selected':''}`} onClick={()=>pick(page,ref)}><span className="ab-nav-index">{index===undefined?'':String(index+1).padStart(2,'0')}</span><span>{title(page)}{page==='paywall'&&ref?` · ${graph.nodes.filter(n=>n.page==='paywall').findIndex(n=>n.configRef===ref)+1}`:''}</span>{editableScopes&&!editableScopes.includes(page==='paywall'?'paywall':page)&&<small>线上</small>}</button>
 const memberSlot=slots.find(s=>s.members),memberContent=memberSlot&&effectiveContent(value,memberSlot.id)
 const translated=memberContent?.pageTranslations?.[language]?.[node]??{}
 return <div className="ab-plan-editor ab-content-workspace">
 <div className="ab-standard-toolbar"><div><span className="ab-toolbar-label">首次使用流程</span><div className="ab-standard-switch">{flowStandards.map(t=><button type="button" key={t.id} disabled={flowLocked} aria-pressed={value.flowId===t.id} className={value.flowId===t.id?'is-active':''} onClick={()=>{onChange({...value,flowId:t.id});pick(t.standard==='REGISTER_FIRST'?'auth':'value')}}>{t.name}</button>)}</div></div><Button onClick={()=>setFlowOpen(true)}>{flowLocked?'查看流程规则':'配置流程顺序'}</Button></div>
 <div className="ab-content-layout"><aside className="ab-page-directory"><div className="ab-directory-heading"><strong>流程页面</strong></div>{units.map((u,i)=><div key={u.nodes[0].id}>{u.onboarding?<div className="ab-nav-module"><div className="ab-nav-module-title">{i+1}. Onboarding · 内部顺序固定</div>{u.nodes.map(n=><div key={n.id}>{pageButton(n.page)}</div>)}</div>:pageButton(u.nodes[0].page,u.nodes[0].configRef??'',i)}</div>)}<div className="ab-directory-heading ab-directory-secondary"><strong>关联页面</strong></div>{['value','auth','auth-after','paywall','retention-promo','retention-regular',...(!graph.nodes.some(n=>n.page==='lesson')?['lesson']:[])].map(page=><div key={page}>{pageButton(page)}</div>)}<p className="ab-directory-note">后置登录按游客会员状态自动触发。购买页每次出现可独立配置；关联主购买页用于默认场景。</p></aside>
 <section className="ab-page-workarea"><div className="ab-content-toolbar"><div><h3>{title(selected.page)}{selected.ref?' · 流程内独立配置':''}</h3><Typography.Text type="secondary">{isLesson?'选择体验课版本；页面布局、图文与交互沿用 App。':'文案留空或隐藏素材时不展示对应元素；品牌与业务规则固定。'}</Typography.Text></div>{!isLesson&&<Space><Button onClick={()=>setTranslationsOpen(true)}>多语言校对</Button><Select aria-label="编辑与预览语言" value={language} onChange={setLanguage} options={productLanguages} style={{width:175}}/></Space>}</div>
 {pageLocked&&!readOnly&&<Alert className="ab-page-readonly" type="info" message="此页面不在实验测试范围，运行时沿用最新线上内容。可在实验设置中加入测试范围。"/>}
 {isPaywall&&<Space className="ab-scene-toolbar"><Select aria-label="购买页设备" value={device} onChange={setDevice} options={[{value:'phone',label:'手机'},{value:'pad',label:'Pad 横屏'}]}/><Select aria-label="购买页场景" value={scene} onChange={setScene} options={[{value:'regular',label:'普通购买页'},{value:'promo',label:'Promo 购买页'}]}/><Button type={!member?'primary':'default'} onClick={()=>setMember(false)}>页面与商品</Button><Button type={member?'primary':'default'} onClick={()=>setMember(true)}>会员权益</Button></Space>}
 {!!issues.length&&!isLesson&&<Alert type="error" showIcon message="当前页面待完善" description={<ul>{[...new Set(issues)].map(x=><li key={x}>{x}</li>)}</ul>}/>}
 {isLesson?<ABTrialLessonEditor content={effectiveContent(value,slots[0].id)} target={target} readOnly={pageLocked} experiment={!!editableScopes} legacy={readOnly&&!value.contents[slots[0].id]} onChange={c=>update({[slots[0].id]:c})}/>:member&&memberSlot&&memberContent?<ABMemberEditor value={memberContent.details.members??[]} readOnly={pageLocked} language={language} baseLanguage={memberContent.baseLanguage??'en'} text={(key,base)=>language===(memberContent.baseLanguage??'en')?base:translated[key]??base} onChange={members=>update({[memberSlot.id]:{...memberContent,details:{...memberContent.details,members}}})} onText={(key,text)=>update({[memberSlot.id]:{...memberContent,pageTranslations:{...memberContent.pageTranslations,[language]:{...memberContent.pageTranslations?.[language],[node]:{...translated,[key]:text}}}}})}/>:slots.length?<ABPageEditor key={`${node}-${selected.ref}-${value.flowId}`} appMode compact expandAll={issues.length>0} plan={plan} node={node} target={target} readOnly={pageLocked} language={language} sectionKeys={[...new Set(slots.filter(s=>!s.members).map(s=>s.section))]} onChange={p=>update(Object.fromEntries(slots.filter(s=>!s.members).map(s=>[s.id,extractContent(p,s)])))}/>:<Card><Empty description={`${title(selected.page)}沿用 App 页面，无需配置素材。`}/></Card>}
 </section></div><Drawer title="多语言校对" width={720} open={translationsOpen} onClose={()=>setTranslationsOpen(false)}><ABTranslationReview items={slots.map(slot=>({slot,content:effectiveContent(value,slot.id)}))} readOnly={pageLocked} onChange={(id,c)=>update({[id]:c})}/></Drawer><Drawer title="流程编排与依赖校验" width="94vw" open={flowOpen} onClose={()=>setFlowOpen(false)} footer={<Button type="primary" onClick={()=>setFlowOpen(false)}>完成编排</Button>}><ABFlowEditor key={value.flowId} value={graph} readOnly={flowLocked} onChange={flow=>update({[value.flowId]:{...flowContent,flow,steps:flow.nodes.map(n=>n.page)}})}/></Drawer></div>
}
