const assert = require('node:assert/strict')
const { mkdtempSync, symlinkSync, rmSync } = require('node:fs')
const { tmpdir } = require('node:os')
const { resolve, join } = require('node:path')
const { execFileSync } = require('node:child_process')
const tmp = mkdtempSync(join(tmpdir(), 'crm-phase5-tests-'))
try {
  execFileSync(resolve('node_modules/.bin/tsc'), ['src/phase5.ts', 'src/phase5Orders.ts', '--outDir', tmp, '--module', 'commonjs', '--moduleResolution', 'node', '--target', 'ES2020', '--esModuleInterop', '--skipLibCheck'], { stdio: 'inherit' })
  symlinkSync(resolve('node_modules'), join(tmp, 'node_modules'), 'dir')
  const { assignLeads, canReceiveLead, withPhase5Members } = require(join(tmp, 'phase5.js'))
  const { matchesOrderFilters5, orderCreatedTime, orderTime5 } = require(join(tmp, 'phase5Orders.js'))
  const target = { id: 'cc', name: '真实销售', email: 'cc@test.invalid', roleId: 'sales', isSalesMember: true, status: '启用', businessLines: ['越南'] }
  const roles = [{ id: 'sales', dataScope: 'line', perms: { salesV3: 'operate' } }]
  assert(canReceiveLead(target, roles, '越南'))
  assert(!canReceiveLead(target, roles, '韩国'))
  assert(!canReceiveLead({ ...target, isSalesMember: false }, roles, '越南'), 'page permission alone is insufficient')
  assert(!canReceiveLead({ ...target, status: '停用' }, roles, '越南'))
  assert(!canReceiveLead(target, [{ ...roles[0], perms: { salesV3: 'view' } }], '越南'))
  const marked = withPhase5Members({ accounts: [{ ...target, isSalesMember: false, id: 'management-demo-cc-1' }, { ...target, isSalesMember: undefined, id: 'real-staff' }] })
  assert.equal(marked.accounts[0].isSalesMember, false, 'preserve explicit member choices')
  assert.equal(marked.accounts[1].isSalesMember, false, 'never guess real sales membership from page access')
  const lead = { studentId: 'one', name: 'One', phone: '12345678', businessLine: '越南', status: '未付费-未体验', salesOwner: 'old@test.invalid', salesProgress: '暂不跟进', salesLatestNote: '用户下周有时间', salesHistory: [{ note: 'old history' }], salesAppointments: [{ appointmentId: 'original' }], salesLifecycleEvents: [{ eventId: 'original' }] }
  const state = { students: [lead, { ...lead, studentId: 'same', salesOwner: target.email }, { ...lead, studentId: 'paid', status: '付费' }, { ...lead, studentId: 'foreign', businessLine: '韩国' }], accounts: [target], roles, channels: [], lessons: [], logs: [] }
  const request = { records: [...state.students, state.students[0]], target: target.email, actor: 'manager', source: '销售中心五期', scope: ['越南'], permitted: true, seeAllOwners: true, reason: '轮岗', now: '2026-09-20 09:00:00' }
  const result = assignLeads(state, request)
  assert.deepEqual(result.results.map(r => r.status), ['成功', '跳过', '失败', '失败'])
  assert.equal(result.state.students[0].salesOwner, target.email)
  assert.equal(result.state.students[0].ccName, target.name)
  assert.equal(result.state.students[0].salesProgress, '暂不跟进')
  assert.equal(result.state.students[0].salesLatestNote, lead.salesLatestNote)
  assert.deepEqual(result.state.students[0].salesAppointments, lead.salesAppointments)
  assert.deepEqual(result.state.students[0].salesLifecycleEvents, lead.salesLifecycleEvents)
  assert.equal(result.state.students[0].salesHistory.length, 2)
  assert.equal(result.state.students[0].editHistory[0].changes[0].field, 'CC')
  assert.equal(result.state.logs.length, 1)
  assert.equal(state.students[0].salesOwner, 'old@test.invalid', 'input state is immutable')
  assert.equal(assignLeads(result.state, request).results[0].status, '失败', 'stale original owner cannot overwrite transfer')
  assert.equal(assignLeads(state, { ...request, permitted: false }).state.logs.length, 0)
  assert.equal(assignLeads(state, { ...request, seeAllOwners: false }).results[0].status, '失败')
  assert.equal(assignLeads(state, { ...request, source: '用户中心五期', seeAllOwners: false }).results[0].status, '成功', 'user center permission is independent of existing reassign permission')
  assert.equal(assignLeads({ ...state, accounts: [{ ...target, status: '停用' }] }, request).results[0].status, '失败')
  const pool = { ...lead, studentId: 'pool', salesOwner: undefined, salesProgress: '待领取' }
  const allocated = assignLeads({ ...state, students: [pool] }, { ...request, records: [pool] })
  assert.equal(allocated.state.students[0].salesProgress, '跟进中')
  const order = { orderId: 'o', currency: 'VND', paidAmount: 100, productName: 'A', paidTime: '2026-09-19 16:00:00', transactions: [{ time: '2026-09-02 01:00:00' }, { time: '2026-09-01 01:00:00' }] }
  assert.equal(orderCreatedTime(order), '2026-09-01 01:00:00')
  assert.equal(orderTime5(order.paidTime), '2026-09-20 00:00')
  const filters = { dateField: 'paidTime', from: '2026-09-20', to: '2026-09-20' }
  assert(matchesOrderFilters5(order, filters))
  assert(!matchesOrderFilters5({ ...order, paidTime: '2026-09-19 15:59:59' }, filters))
  assert(matchesOrderFilters5({ ...order, paidTime: '2026-09-20 15:59:59' }, filters))
  assert(!matchesOrderFilters5({ ...order, paidTime: '2026-09-20 16:00:00' }, filters))
  assert(!matchesOrderFilters5({ ...order, paidTime: undefined }, filters))
  assert(matchesOrderFilters5(order, { dateField: 'createdTime', from: '2026-09-01', to: '2026-09-01' }))
  assert(!matchesOrderFilters5(order, { dateField: 'paidTime', currency: 'USD' }))
  assert(!matchesOrderFilters5(order, { dateField: 'paidTime', cc: 'other' }, target.email))
  assert(matchesOrderFilters5(order, { dateField: 'paidTime', cc: '__unassigned__' }))
  console.log('Phase 5 checks passed: explicit sales membership, transfer authorization/scope/concurrency/history, batch outcomes, order timezone/currency/CC filters.')
} finally { rmSync(tmp, { recursive: true, force: true }) }
