import { useI18n } from './i18n'
const words = {
 ratesReference: ['参考转化率', 'Reference conversion rates'],
 ratesReferenceHelp: ['按同一批线索的现有记录计算；历史记录不完整，比例仅供参考。分母为 0，或后续环节用户缺少前一环节记录时，显示无法计算。', 'Calculated from recorded outcomes for the same lead group. History is incomplete, so these are reference ratios. A zero denominator or missing records in the preceding step makes a rate unavailable.'],
 rateUnavailable: ['无法计算', 'Unavailable'], zeroDenominator: ['分母为 0', 'Denominator is zero'], missingHistory: ['后续环节用户缺少前一环节记录', 'Some users have no record in the preceding step'],
 revenueAov: ['实付金额 / AOV', 'Amount paid / AOV'], orderAverage: ['平均订单金额（AOV）', 'Average order value (AOV)'], orderAverageHelp: ['实付金额 ÷ 已支付订单数', 'Amount paid ÷ paid orders'],
 dateCC: ['日期 → CC', 'Date → CC'], dateCCHelp: ['展开日期查看各 CC 当天对应的数据。归属按当前 CC，转交后会变化。', 'Expand a date to see each CC. Attribution uses the current CC and changes after reassignment.'],
 tablePaymentCurrent: ['金额和 AOV 对应这些注册用户截至现在的有效已支付订单；不是注册当天的收款。不同币种分别展示。', 'Amount and AOV use valid paid orders to date for these registered users, not payments on their registration day. Currencies remain separate.'],
 tablePaymentPeriod: ['金额和 AOV 按支付日期统计，AOV = 实付金额 ÷ 已支付订单数。不同币种分别展示。', 'Amount and AOV use payment dates. AOV = amount paid ÷ paid orders. Currencies remain separate.'],
 allSources: ['全部渠道', 'All sources'], sourceMappingHelp: ['渠道沿用 CRM 现有来源；Multi-cities、2 Cities 等业务分类尚未确认对应关系。', 'Sources use existing CRM values. Business categories such as Multi-cities and 2 Cities have not been mapped yet.'],
 viewCurrent: ['线索现状', 'Current leads'], viewPeriod: ['销售活动', 'Sales activity'], viewCohort: ['转化总览', 'Conversion overview'], viewPayments: ['支付结果', 'Payments'],
 questionCurrent: ['现在跟进到哪一步？', 'Where do leads stand now?'], questionPeriod: ['CC 每天做了什么？', 'What did each CC do each day?'], questionCohort: ['各 CC 的线索转化得怎样？', 'How do leads convert by CC?'], questionPayments: ['这段时间收到多少钱？', 'How much was paid in this period?'],
 chooseQuestion: ['选择要了解的问题', 'Choose a question'], readingGuide: ['这一页怎么读', 'How to read this view'],
 readCurrent: ['当前销售线索共 {total} 人，其中 {assigned} 人已分配、{unassigned} 人未分配。下方 9 个阶段合计就是这 {total} 人；已支付用户单独统计。', 'There are {total} current leads: {assigned} assigned and {unassigned} unassigned. The nine stages below add up to these {total} leads. Paid users are counted separately.'],
 readPeriod: ['所选期间，{called} 人有外呼记录、{connected} 人有接通记录、{paid} 人有成功支付。一个人可以出现在多项活动中，各项人数不能相加，也不代表逐步转化。', 'In the selected period, {called} users were called, {connected} were reached and {paid} paid. One person may appear in several activities. These counts cannot be added together or read as a conversion funnel.'],
 readCohort: ['这批线索共 {leads} 人，其中 {paid} 人已有有效支付订单，总付费转化率为 {totalRate}（参考）。下表每行比较一批人的跟进结果，人数下方的百分比说明对应环节的转化。', 'This group contains {leads} leads, including {paid} with valid paid orders: a reference lead-to-payment rate of {totalRate}. Each row compares one group; the percentage below a count describes conversion at that step.'],
 readPayments: ['先看所选支付日期内的实付金额，再看付款人数和每单平均金额（AOV）。人均支付金额另外列出；同一用户多笔订单只算一人，金额按币种分别查看。', 'Start with the amount paid in the selected payment dates, then payers and average order value (AOV). Amount per payer is listed separately. Multiple orders from one user count as one payer; currencies remain separate.'],
 nextCurrent: ['接下来：看未分配、待外呼和待支付人数，再按 CC 找到具体用户。点击蓝色数字可以继续跟进。', 'Next: check unassigned leads, leads awaiting a call and leads awaiting payment. Break down by CC, then select a blue count to follow up.'],
 nextPeriod: ['接下来：按 CC 看各自的活动记录，或按日期看每天发生的活动；点击人数核对用户。', 'Next: compare recorded activity by CC or inspect it by day. Select a count to view the users.'],
 nextCohort: ['接下来：展开日期比较各 CC 的转化。要看 CC 当天做了多少工作，切换到销售活动。', 'Next: expand a date to compare CC conversion. For the work each CC did on a particular day, switch to Sales activity.'],
 nextPayments: ['接下来：按 CC 或支付日期查看明细，点击金额或订单数核对成功订单。', 'Next: view details by CC or payment date. Select an amount or order count to inspect the paid orders.'],
 exampleTitle: ['用一个用户理解四种看法', 'One user, four views'], exampleIntro: ['例：小明 9 月 1 日注册，9 月 5 日接通，9 月 10 日支付。', 'Example: Minh registers on Sep 1, is reached on Sep 5 and pays on Sep 10.'],
 exampleCurrent: ['支付后，当前线索不再计入他；已支付用户中计 1 人。', 'After payment, he leaves current leads and counts as one paid user.'],
 examplePeriod: ['看 9 月 5 日，接通人数中计 1 人；看 9 月 10 日，支付人数中计 1 人。', 'For Sep 5 he counts as one user reached; for Sep 10 he counts as one paid user.'],
 exampleCohort: ['选择 9 月 1 日注册的线索，能看到他后来的接通和支付记录。', 'Selecting leads registered on Sep 1 includes his later contact and payment records.'],
 examplePayments: ['他的订单金额计在 9 月 10 日，与注册日期无关。', 'His order amount counts on Sep 10, regardless of registration date.'],
 dateCurrentMeaning: ['日期选择的是哪天注册的用户；下面看的是他们现在的状态。', 'Dates select when users registered; the data below shows their status now.'],
 datePeriodMeaning: ['日期选择的是活动发生的期间；可以包含更早注册的用户。', 'Dates select the activity period; users may have registered earlier.'],
 dateCohortMeaning: ['日期选择的是同一批注册线索；后续跟进记录一直看到现在。', 'Dates select one group of registered leads; follow-up records include later activity to date.'],
 datePaymentsMeaning: ['日期选择的是订单支付时间；不按用户注册时间筛选。', 'Dates select when orders were paid, regardless of user registration dates.'],
 overview: ['整体情况', 'Overview'], scope: ['越南 · 正式用户 · UTC+7', 'Vietnam · Production users · UTC+7'],
 demoTag: ['演示数据', 'Demo data'], rules: ['统计说明', 'Counting rules'],
 resetFilters: ['重置筛选', 'Reset filters'], today: ['今天', 'Today'], last7: ['近 7 天', 'Last 7 days'], thisMonth: ['本月', 'This month'],
 groupIntent: ['按购买意向', 'By purchase intent'], groupAge: ['按年龄段', 'By age group'], groupRegistrationAge: ['按注册时长', 'By time since registration'],
 groupSource: ['按渠道来源', 'By channel source'], source: ['渠道来源', 'Channel source'],
 revenueTitle: ['支付金额', 'Payments'],
 revenueHelp: ['按支付日期统计当前仍为已支付的订单，同一用户多笔订单只计一人。不同币种分别展示；退款后移除对应订单，并重算原支付日期的金额。此处不是财务净收入。', 'Count orders currently marked Paid by payment date, with each payer counted once. Currencies are shown separately. Refunded orders are removed and the original payment period is restated. This is not accounting net revenue.'],
 revenue: ['实付金额', 'Amount paid'], aov: ['人均支付金额', 'Amount per paying user'], paidDate: ['支付日期', 'Payment date'], paidOrders: ['已支付订单', 'Paid orders'], paidUsers: ['已支付用户', 'Paid users'],
 allMetrics: ['显示全部指标', 'Show all metrics'], allMetricsHelp: ['全部指标已展示；可左右滚动查看，或按需选择显示指标。', 'All metrics are shown. Scroll horizontally to view them, or choose which metrics to display.'], visibleColumns: ['显示指标', 'Visible metrics'], columnsUnit: ['项指标', 'metrics'],
 cohortTitle: ['这批线索的跟进进展', 'Progress of this lead group'],
 sourceDateTitle: ['每天从哪些渠道获得线索？', 'Which sources bring leads each day?'], sourceCCTitle: ['各渠道的线索由谁负责？', 'Who owns the leads from each source?'],
 sourceDateHelp: ['按注册日期 × 渠道来源统计同一批线索，包含后来已付费的用户。', 'The same lead group by registration date and source, including users who later paid.'], sourceCCHelp: ['按当前 CC × 渠道来源统计；用户转交后归入新的 CC，不代表历史分配情况。', 'The same leads by current CC and source. Reassigned users move to the new CC; this is not historical allocation.'],
 progressCompare: ['按日期和 CC 比较转化', 'Compare conversion by date and CC'], progressCompareHelp: ['每一行都看同一批人的线索、接通、预约、出席和支付人数。数字下方是该环节的参考转化率；展开查看下一层，点击人数核对用户。', 'Each row follows the same lead group. Reference conversion rates appear below the counts. Expand for the next level, or select a count to inspect users.'],
 cohortHelp: ['按注册日期选定同一批线索（包含后来已付费的用户），查看截至目前有记录的接通、预约、出席和支付人数。后续记录不受注册日期范围限制；不等同于当前阶段或期间活动人数。', 'Select the same lead population by registration date, including users who later paid. Count recorded contact, booking, attendance and payment outcomes to date, including records after the registration range. These are not current stages or activity-period counts.'],
 cohortEvidence: ['接通看通话或接通登记，预约看创建或预约登记，出席看出席或咨询结果登记；取消预约仍计入曾预约。缺少历史登记不能当作未发生，不从当前状态推算历史。支付以有效已支付订单为准。', 'Contact uses call or contact records; booking uses creation or booking records; attendance uses attendance or consultation records. Cancelled bookings still count as past bookings. Missing records do not prove an outcome never happened; current statuses do not reconstruct history. Payments require valid paid orders.'],
 cohortLeads: ['线索数（含已付费）', 'Leads (including paid)'], cohortConnected: ['接通人数', 'Users reached'], cohortBooked: ['预约人数', 'Users with bookings'], cohortAttended: ['出席人数', 'Users attended'],
 primaryDimension: ['先按', 'Group first by'], secondaryDimension: ['再按', 'Then by'], noSecondary: ['不再细分', 'No subgroup'],
 hierarchyHelp: ['展开每行查看下一层分组；点击人数查看对应用户。', 'Expand a row to see its subgroup. Select a count to view matching users.'],
 cohortDateHelp: ['本区按注册日期筛选，与上方销售活动日期分别设置；CC 共用上方筛选。', 'This section has its own registration dates, separate from activity dates above. The CC filter is shared.'],
 paymentDateHelp: ['本区按支付日期筛选，与上方注册日期分别设置；CC 共用上方筛选。', 'This section has its own payment dates, separate from registration dates above. The CC filter is shared.'],
 conversionStatus: ['历史转化率待记录补齐后提供。', 'Historical conversion rates await complete records.'],
 ratesTitle: ['各环节转化率', 'Conversion at each step'], ratePending: ['待补齐', 'Pending history'], rateContact: ['接通率', 'Contact rate'], rateBooking: ['预约率', 'Booking rate'], rateAttendance: ['出席率', 'Attendance rate'], ratePaid: ['出席付费率', 'Attendance-to-payment'], rateTotal: ['总付费转化率', 'Lead-to-payment'],
 conversionRules: ['转化率口径', 'Conversion definitions'],
 conversionDeferred: ['历史记录尚不完整，暂不展示转化率。补齐后，按同一批线索和以下公式统计；当前阶段占比和销售活动人数不用于计算转化率。', 'Conversion rates are deferred until complete history is available. They will use the same lead population and the formulas below, not current-stage shares or independent activity counts.'],
 connectFormula: ['接通率 = 接通人数 ÷ 线索数', 'Contact rate = users reached ÷ leads'],
 bookFormula: ['预约率 = 预约人数 ÷ 接通人数', 'Booking rate = users with bookings ÷ users reached'],
 attendanceFormula: ['出席率 = 出席人数 ÷ 预约人数', 'Attendance rate = users attended ÷ users with bookings'],
 attendancePaidFormula: ['出席付费率 = 付费人数 ÷ 出席人数', 'Attendance-to-payment rate = paying users ÷ users attended'],
 totalPaidFormula: ['总付费转化率 = 付费人数 ÷ 线索数', 'Lead-to-payment rate = paying users ÷ leads'],
 totalHint: ['已分配 + 未分配', 'Assigned + unassigned'], assignedHint: ['已有负责 CC', 'Has an assigned CC'], unassignedHint: ['需要安排负责 CC', 'Needs a CC assignment'],
 registeredHint: ['按注册时间 · 人数', 'By registration time · users'], calledHint: ['按通话时间 · 人数', 'By call time · users'], connectedHint: ['按通话时间 · 人数', 'By call time · users'], bookedHint: ['按预约创建时间 · 人数', 'By booking creation time · users'], attendedHint: ['按出席结果登记时间 · 人数', 'By attendance record time · users'], completedHint: ['按咨询结果登记时间 · 人数', 'By consultation record time · users'],
 currency: ['币种', 'Currency'], unknownCurrency: ['币种未填写', 'Currency not recorded'],
 paymentDetails: ['支付明细', 'Payment details'], paymentOrders: ['订单明细', 'Order list'], allUsers: ['全部用户', 'All users'], allPayments: ['全部支付', 'All payments'],
 paymentScope: ['仅包含所选日期、CC 和币种内的已支付订单。', 'Only paid orders matching the selected dates, CC and currency.'],
 averageHelp: ['实付金额 ÷ 已支付用户数', 'Amount paid ÷ distinct paying users'],
 noPayments: ['所选范围内暂无已支付订单。', 'No paid orders in this selection.'],
 paymentTotal: ['所选范围合计', 'Selection total'],
 intent: ['购买意向', 'Purchase intent'], age: ['年龄段', 'Age group'], registrationAge: ['距注册天数', 'Days since registration'], unknown: ['未填写', 'Not recorded'], days: ['天', 'days'],
 groupHelp: ['按用户当前填写的信息拆分同一组指标；未填写的单独列出。点击人数查看用户。', 'Split the same metrics by the information currently recorded for each user. Missing values are listed separately. Select a count to view users.'],
 registrationAgeHelp: ['按距今天的注册天数分组，不代表在当前阶段停留的天数，也不等同于业务表中的 Old Lead。', 'Group by days since registration as of today. This is not time spent in a stage or the business sheet’s Old Lead label.'],
 reasons: ['跟进原因', 'Follow-up reasons'], noShow: ['未出席', 'No-show'], incomplete: ['咨询未完成', 'Incomplete consultation'], paused: ['暂不跟进', 'Paused'], closed: ['已关闭', 'Closed'],
 reason: ['原因', 'Reason'], usersCount: ['用户数', 'Users'], share: ['占比', 'Share'],
 currentReasonHelp: ['只看当前处于所选阶段的用户，使用最近一次对应记录的原因。未记录的单独列出。', 'Users currently in the selected stage, using the reason from their latest matching record. Missing reasons are listed separately.'],
 periodReasonHelp: ['按原因登记时间统计，每个原因内按用户去重。同一用户可能有多个原因，各行人数不能直接相加。', 'Count by the date the reason was recorded. Users are deduplicated within each reason and may appear in more than one row.'],
 noReasons: ['所选范围暂无对应记录。', 'No matching records in this selection.'],
 formalOnly: ['统一统计正式用户，排除测试用户。按当前 CC 归属查看，转交后会随当前负责人变化。', 'Only production users are counted. Users are grouped by their current CC, including after reassignment.'],
 limits: ['参考转化率基于现有记录，历史完整性尚未确认。定金及尾款暂不展示。支付金额反映有效已支付订单，未完成财务对账。', 'Reference conversion rates use available records; historical completeness is unverified. Deposits and balances are deferred. Payment amounts reflect valid paid orders and are not financially reconciled.'],
 intentNote: ['购买意向是 CC 当前填写的判断，不代表付款概率。', 'Purchase intent is the CC’s recorded assessment, not a payment probability.'],
 stageShare: ['占当前线索', 'of current leads'],
 paid: ['已支付用户', 'Paid users'],
 paidCurrent: ['所选日期注册、已有成功支付的用户；不计入当前线索。', 'Registered in the selected dates and has a successful payment; excluded from current leads.'],
 paidPeriod: ['按支付日期 · 同一用户只计一人', 'By payment date · distinct users'],
 paidRule: ['已支付用户以订单为准：当前订单状态为已支付、实付金额大于 0，且有有效支付时间。按用户 ID 去重，排除待支付、已取消、已退款及零元订单。当前阶段视角按注册日期筛选，销售活动视角按支付日期筛选；退款后会从相应统计中移除。用户付费标记不替代订单。', 'Paid users require an order currently marked Paid, a positive amount and a valid payment time. Count distinct user IDs, excluding pending, cancelled, refunded and zero-value orders. The current view filters by registration date; the activity view filters by payment date. Refunded orders are removed from the corresponding counts. A profile payment flag is not a substitute for an order.'],
 title: ['销售管理看板', 'Sales management dashboard'],
 subtitle: ['先选一个业务问题，再看对应的数据和用户。', 'Choose a business question, then explore the relevant data and users.'],
 current: ['当前阶段分布', 'Current stage distribution'], period: ['销售活动统计', 'Sales activity'],
 currentHelp: ['查看所选日期注册的用户现在跟进到哪一步；已支付用户单独统计。', 'See the current follow-up stages of users registered in the selected dates. Paid users are counted separately.'],
 periodHelp: ['查看所选日期内发生的销售活动，包含更早注册的用户。各项分别按用户去重，不计算转化率。', 'See sales activity in the selected dates, including users registered earlier. Each metric counts distinct users independently; no conversion rates are calculated.'],
 demo: ['原型演示数据，与销售、用户和订单中心共用。未连接测试或正式数据库。', 'Demo data shared with Sales, User and Order Centers. No test or production database is connected.'],
 allCC: ['全部 CC', 'All CCs'], unassigned: ['未分配', 'Unassigned'], assigned: ['已分配', 'Assigned'], total: ['当前销售线索', 'Current sales leads'],
 allDates: ['全部日期', 'All dates'],
 registerDates: ['注册日期', 'Registration dates'], recordDates: ['统计日期', 'Activity dates'],
 stageTitle: ['当前跟进阶段', 'Current follow-up stage'], stageHelp: ['每条线索只计入一个阶段。点击人数查看用户并继续跟进。', 'Each lead belongs to one stage. Select a count to view users and follow up.'],
 breakdown: ['销售活动明细（期间去重人数）', 'Sales activity detail (distinct users in period)'], currentBreakdown: ['当前线索明细', 'Current lead breakdown'], dateTitle: ['按日期查看', 'By date'],
 dateCurrentHelp: ['按用户注册日期分组，查看这些用户现在的阶段，不是当天的历史阶段。仅列出有数据的日期。', 'Group users by registration date and show their stages now, not their stages on that past date. Only dates with data are shown.'],
 datePeriodHelp: ['按各项活动的统计日期分组，每天按用户 ID 去重；同一用户可在多天出现，因此各天人数相加可能大于期间总人数。仅列出有数据的日期。', 'Group each activity by its counting date, deduplicating users within each day. A user may appear on several days, so daily counts can exceed the distinct users for the whole period. Only dates with data are shown.'],
 periodTotal: ['期间去重人数', 'Distinct users in period'], currentTotal: ['合计', 'Total'],
 ccTitle: ['按 CC 查看', 'By CC'], ccHelp: ['按当前归属 CC 拆分上方指标，未分配用户单独列出。', 'The same metrics grouped by current CC. Unassigned users appear separately.'],
 registered: ['新注册线索', 'New leads'], called: ['外呼用户', 'Users called'], connected: ['接通用户', 'Users reached'], booked: ['创建预约用户', 'Users with bookings'], attended: ['登记出席用户', 'Attendance recorded'], completed: ['登记咨询完成用户', 'Consultations recorded'],
 periodNote: ['注册按注册时间、外呼和接通按通话时间、预约按创建时间；出席和咨询完成按登记时间统计。未记录的历史结果无法补算。', 'Registration uses registration time; calls use call time; bookings use creation time. Attendance and consultation completion use the time recorded. Missing historical records cannot be reconstructed.'],
 unavailable: ['暂不展示历史转化率、付费转化率和 CC 付费排名。', 'Historical conversion rates, paid conversion and CC payment rankings are not included.'],
 users: ['用户明细', 'User details'], count: ['位用户', 'users'], currentCC: ['当前 CC', 'Current CC'], salesAction: ['销售跟进', 'Sales follow-up'], userAction: ['用户详情', 'User details'], orderAction: ['用户订单', 'User orders'],
 back: ['返回管理看板', 'Back to dashboard'], clear: ['清除用户筛选', 'Clear user filter'],
 filtered: ['已按用户 ID 筛选', 'Filtered by User ID'], noRows: ['暂无符合条件的用户，请调整日期或 CC。', 'No matching users. Try changing the dates or CC.'],
 noOrders: ['该用户暂无符合条件的订单。', 'No matching orders for this user.'],
 orderDetail: ['订单详情', 'Order details'], orderTransactions: ['订单流水', 'Order transactions'], backOrders: ['返回订单中心', 'Back to Order Center'],
 ordersIntro: ['点击订单 ID 查看订单详情及全部交易流水。', 'Select an order ID to view its details and all transactions.'],
 noOrder: ['未找到该订单，或你没有访问权限。', 'This order was not found or you do not have access.'],
 subOrder: ['子订单号', 'Transaction ID'], recordTime: ['发生时间', 'Time'], amount: ['金额', 'Amount'],
 export: ['导出列表', 'Export list'],
} as const
export type DashboardWord = keyof typeof words
export function useDashboardText() {
 const { lang } = useI18n()
 return (key: DashboardWord, values: Record<string, string | number> = {}) => Object.entries(values).reduce<string>((text, [name, value]) => text.split(`{${name}}`).join(String(value)), words[key][lang === 'zh' || lang === 'zhTW' ? 0 : 1])
}
