import { useI18n } from './i18n'
const words = {
 overview: ['整体情况', 'Overview'], scope: ['越南 · 正式用户 · UTC+7', 'Vietnam · Production users · UTC+7'],
 demoTag: ['演示数据', 'Demo data'], rules: ['统计说明', 'Counting rules'],
 resetFilters: ['重置筛选', 'Reset filters'], today: ['今天', 'Today'], last7: ['近 7 天', 'Last 7 days'], thisMonth: ['本月', 'This month'],
 groupIntent: ['按购买意向', 'By purchase intent'], groupAge: ['按年龄段', 'By age group'], groupRegistrationAge: ['按注册时长', 'By time since registration'],
 groupSource: ['按渠道来源', 'By channel source'], source: ['渠道来源', 'Channel source'], dateCC: ['按日期 × CC', 'By date × CC'],
 groupBy: ['聚合维度', 'Group by'], primaryDimension: ['一级维度', 'Primary dimension'], secondaryDimension: ['二级维度', 'Secondary dimension'], expand: ['展开', 'Expand'], hierarchyHelp: ['先看一级维度汇总，展开后查看二级维度明细；切换顺序即可获得另一种对比视角。', 'Review the primary-dimension total first, then expand for the secondary breakdown. Switch the order for the alternate comparison.'],
 conversionTitle: ['转化漏斗分析', 'Conversion funnel analysis'], cohortTag: ['注册 Cohort', 'Registration cohort'],
 conversionHelp: ['以注册日期为分母，查看线索后续是否接通、预约、出席及付费。可按 CC、统一渠道来源，或日期 × CC 对比效率；各百分比均相对于 Leads。', 'Use registration date as the denominator to see whether leads later connected, booked, attended and paid. Compare efficiency by CC, unified channel source, or date × CC; every rate is relative to Leads.'],
 leads: ['线索数', 'Leads'],
 revenueTitle: ['营收与客单价', 'Revenue & AOV'], revenueHelp: ['仅统计已支付且实付金额大于 0 的订单，按支付日期筛选。AOV = Revenue ÷ 付费用户数。', 'Includes only paid orders with a positive paid amount, filtered by payment date. AOV = Revenue ÷ paid users.'],
 revenue: ['营收', 'Revenue'], aov: ['客单价（AOV）', 'Average order value (AOV)'], paidDate: ['支付日期', 'Paid date'], paidOrders: ['已支付订单', 'Paid orders'], paidUsers: ['付费用户', 'Paid users'],
 intent: ['购买意向', 'Purchase intent'], age: ['年龄段', 'Age group'], registrationAge: ['距注册天数', 'Days since registration'], unknown: ['未填写', 'Not recorded'], days: ['天', 'days'],
 groupHelp: ['按用户当前填写的信息拆分同一组指标；未填写的单独列出。点击人数查看用户。', 'Split the same metrics by the information currently recorded for each user. Missing values are listed separately. Select a count to view users.'],
 registrationAgeHelp: ['按距今天的注册天数分组，不代表在当前阶段停留的天数，也不等同于业务表中的 Old Lead。', 'Group by days since registration as of today. This is not time spent in a stage or the business sheet’s Old Lead label.'],
 reasons: ['跟进原因', 'Follow-up reasons'], noShow: ['未出席', 'No-show'], incomplete: ['咨询未完成', 'Incomplete consultation'], paused: ['暂不跟进', 'Paused'], closed: ['已关闭', 'Closed'],
 reason: ['原因', 'Reason'], usersCount: ['用户数', 'Users'], share: ['占比', 'Share'],
 currentReasonHelp: ['只看当前处于所选阶段的用户，使用最近一次对应记录的原因。未记录的单独列出。', 'Users currently in the selected stage, using the reason from their latest matching record. Missing reasons are listed separately.'],
 periodReasonHelp: ['按原因登记时间统计，每个原因内按用户去重。同一用户可能有多个原因，各行人数不能直接相加。', 'Count by the date the reason was recorded. Users are deduplicated within each reason and may appear in more than one row.'],
 noReasons: ['所选范围暂无对应记录。', 'No matching records in this selection.'],
 formalOnly: ['统一统计正式用户，排除测试用户。按当前 CC 归属查看，转交后会随当前负责人变化。', 'Only production users are counted. Users are grouped by their current CC, including after reassignment.'],
 limits: ['当前数据尚不足以还原完整历史转化和确认销售收入，因此暂不展示转化率、付费排名、定金及尾款。', 'The available data does not establish a complete conversion history or reconciled sales revenue. Conversion rates, paid rankings, deposits and balances are not shown.'],
 intentNote: ['购买意向是 CC 当前填写的判断，不代表付款概率。', 'Purchase intent is the CC’s recorded assessment, not a payment probability.'],
 stageShare: ['占当前线索', 'of current leads'],
 paid: ['已支付用户', 'Paid users'],
 paidCurrent: ['按注册日期筛选；单独统计，不计入当前销售线索。', 'Filtered by registration date; counted separately from current sales leads.'],
 paidPeriod: ['按订单支付日期统计，同一用户多笔支付只计一人。', 'Counted by order payment date; multiple payments by a user count once.'],
 paidRule: ['已支付用户以订单为准：当前订单状态为已支付、实付金额大于 0，且有有效支付时间。按用户 ID 去重，排除待支付、已取消、已退款及零元订单。当前阶段视角按注册日期筛选，销售活动视角按支付日期筛选；退款后会从相应统计中移除。用户付费标记不替代订单。', 'Paid users require an order currently marked Paid, a positive amount and a valid payment time. Count distinct user IDs, excluding pending, cancelled, refunded and zero-value orders. The current view filters by registration date; the activity view filters by payment date. Refunded orders are removed from the corresponding counts. A profile payment flag is not a substitute for an order.'],
 title: ['销售管理看板', 'Sales management dashboard'],
 subtitle: ['看整体进展，找出需要跟进的用户。', 'See overall progress and find users who need follow-up.'],
 current: ['当前阶段分布', 'Current stage distribution'], period: ['销售活动统计', 'Sales activity'],
 currentHelp: ['按注册日期选择当前销售线索，查看其现在的跟进阶段。每位用户只属于一个阶段，不代表历史转化漏斗。', 'Filter current sales leads by registration date and view their stage now. Each user belongs to one stage. This is not a historical conversion funnel.'],
 periodHelp: ['分别统计所选日期内有记录的用户，按用户 ID 去重。同一用户可出现在多项指标中，不能用这些人数计算转化率。', 'Count distinct users with records in the selected dates. A user may appear in several metrics; these counts do not form a conversion funnel.'],
 demo: ['原型演示数据，与销售、用户和订单中心共用。未连接测试或正式数据库。', 'Demo data shared with Sales, User and Order Centers. No test or production database is connected.'],
 allCC: ['全部 CC', 'All CCs'], unassigned: ['未分配', 'Unassigned'], assigned: ['已分配', 'Assigned'], total: ['当前销售线索', 'Current sales leads'],
 allDates: ['全部日期', 'All dates'],
 registerDates: ['注册日期', 'Registration dates'], recordDates: ['统计日期', 'Activity dates'],
 stageTitle: ['当前跟进阶段', 'Current follow-up stage'], stageHelp: ['与销售中心三期使用相同的跟进阶段。点击人数查看用户。', 'Uses the same stages as Sales Center Phase 3. Select a count to view users.'],
 breakdown: ['销售活动明细（期间去重人数）', 'Sales activity detail (distinct users in period)'], currentBreakdown: ['当前线索明细', 'Current lead breakdown'], dateTitle: ['按日期查看', 'By date'],
 dateCurrentHelp: ['按用户注册日期分组，查看这些用户现在的阶段，不是当天的历史阶段。仅列出有数据的日期。', 'Group users by registration date and show their stages now, not their stages on that past date. Only dates with data are shown.'],
 datePeriodHelp: ['按各项活动的统计日期分组，每天按用户 ID 去重；同一用户可在多天出现，因此各天人数相加可能大于期间总人数。仅列出有数据的日期。', 'Group each activity by its counting date, deduplicating users within each day. A user may appear on several days, so daily counts can exceed the distinct users for the whole period. Only dates with data are shown.'],
 periodTotal: ['期间去重人数', 'Distinct users in period'], currentTotal: ['合计', 'Total'],
 ccTitle: ['按 CC 查看', 'By CC'], ccHelp: ['按当前归属 CC 拆分上方指标，未分配用户单独列出。', 'The same metrics grouped by current CC. Unassigned users appear separately.'],
 registered: ['新注册线索', 'New leads'], called: ['外呼用户', 'Users called'], connected: ['接通用户', 'Users reached'], booked: ['创建预约用户', 'Users with bookings'], attended: ['登记出席用户', 'Attendance recorded'], completed: ['登记咨询完成用户', 'Consultations recorded'],
 periodNote: ['注册按注册时间、外呼和接通按通话时间、预约按创建时间；出席和咨询完成按登记时间统计。未记录的历史结果无法补算。', 'Registration uses registration time; calls use call time; bookings use creation time. Attendance and consultation completion use the time recorded. Missing historical records cannot be reconstructed.'],
 unavailable: ['暂不展示历史转化率、付费转化率和 CC 付费排名。', 'Historical conversion rates, paid conversion and CC payment rankings are not included.'],
 users: ['用户明细', 'User details'], count: ['位用户', 'users'], currentCC: ['当前 CC', 'Current CC'], salesAction: ['销售跟进', 'Sales follow-up'], userAction: ['用户详情', 'User details'], orderAction: ['用户订单', 'User orders'],
 back: ['返回管理看板', 'Back to dashboard'], clear: ['清除用户筛选', 'Clear user filter'],
 filtered: ['已按用户 ID 筛选', 'Filtered by User ID'], noRows: ['暂无符合条件的用户，请调整日期或 CC。', 'No matching users. Try changing the dates or CC.'],
 noOrders: ['该用户暂无符合条件的订单。', 'No matching orders for this user.'],
 orderDetail: ['订单详情', 'Order details'], orderTransactions: ['订单流水', 'Order transactions'], backOrders: ['返回订单中心', 'Back to Order Center'],
 ordersIntro: ['点击订单 ID 查看订单详情及全部交易流水。', 'Select an order ID to view its details and all transactions.'],
 noOrder: ['未找到该订单，或你没有访问权限。', 'This order was not found or you do not have access.'],
 subOrder: ['子订单号', 'Transaction ID'], recordTime: ['发生时间', 'Time'], amount: ['金额', 'Amount'],
 export: ['导出列表', 'Export list'],
} as const
export type DashboardWord = keyof typeof words
export function useDashboardText() {
 const { lang } = useI18n()
 return (key: DashboardWord) => words[key][lang === 'zh' || lang === 'zhTW' ? 0 : 1]
}
